// Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
// Available under the MIT License - see LICENSE.txt for details.

// This file was generated by `generate_verilog.py`.

`timescale 1ns/1ps

module xormix48_tb;
    
    // configuration
    localparam streams = 4;
    localparam results = 100;
    localparam [47 : 0] seed_x =
        48'h6628a302e856;
    localparam [48 * streams - 1 : 0] seed_y =
        192'hfb9cd8807a15a8c2e722a2a3c3c4bac365bea0720bfb3dce;
    
    // reference result
    localparam [48 * streams * results - 1 : 0] ref_result = {
        192'h0271d530e0db8336ac4758b7df61bf5307af7f2e1648eb35,
        192'hfc60723fea5611d60df93cba7cae281793308e2964d87031,
        192'h12f30a735fe4a483ac16f1c77962b1bd15fb48cc3d5ac0c5,
        192'h78e9fafdabf1be8dd8d5487b83927a194b3062f5a804d657,
        192'hcdd86100e70fe7a6dfb66832ccf08c23f95aa93ee0703be6,
        192'h57d1508dca00e57ed797fd7f827f99ff2ae84b4076e58de6,
        192'h042e4656907e05dfd785b4dfe85ce690545ceda28711f435,
        192'h4c1f2845aa78b90dc78da0a850f205c02be9dcd8496b11c8,
        192'h6fce09834f6f5f7e4768609f56bd429c801902dd8c4d55e9,
        192'h2578997c1c6f272f5907199dcdd60cbd5b5a5a4131743819,
        192'h178833cb3102d6ea2410b1b9467e4adfa9e15b868e74f5bb,
        192'hc881f6160fa8ab13183103742dc6a158c438ca7c4e3d1543,
        192'hee7e4db3ce042127d727d98e5347c39295df4c157e744b26,
        192'hd41a37fa719bf9ca533891236802464935d23ecde14320bb,
        192'h632aadf0946ba41fe402700e96b4181525ea54166af3f5d2,
        192'h8e7dca0526454f869e718e8f71ba7f1d84d68d5bea097c39,
        192'h78cf4926d449c728b8c4a3f59b8b9856baa8e5bfe3187327,
        192'h123ac975cfeab53dfd136b4756d11cf04d9a274d092de4c3,
        192'h6e6ea461ca5c7b7a86c025a7b893f90db4e98cfef096ffc9,
        192'h54c85abfc53e8a60a6e05ae290ff0b90aac62f88d8584c37,
        192'hf627bd8799a3f1a31a39a056cfbfd1ecabeb09d2ef353699,
        192'h388ae312d0b2633980dce120f21e6e2d2947c8f514f96d09,
        192'h2468a61d631d74f915351e8dbe4c3ff0938ea8577492fa0c,
        192'h8ac9de1391891a7281a8063b635d9228c134688a0bc8e257,
        192'h41e6ce9b5bf9fdd9ab928dbe5da8939177f253973ca6e166,
        192'heb07d2ce795f06096df2d3d2d7fef16da679e9b316a24538,
        192'h2d2a01decfb6cfc426ff72f2cdc51010f551a4cb23ff617d,
        192'h73f47defba3a1eca8fa5986773a5707b88826ff2771f5ed2,
        192'h1c292600487cfdb4684bc9ef8d19c9b0fecb621aeb47382a,
        192'hecc0ea1aac44d7ac787ef532cb14b309c6e1ccca25e5806e,
        192'hbb29051a0e5dccb52d8d5cea03671eb44c517d9aa07f8073,
        192'h47101fd9781f2d477b7104cf06e6731090d2fbf2eabcdcc4,
        192'h6c5f57e5161a7bbd42f0abf5ae6f8800da2aea67b9932581,
        192'hcdc851e8c56c05fd0f594648cfe446f196bd9c6461e91c64,
        192'h9f7f7359d36b65555aa68c53c780ff7fea166b89e47fa756,
        192'hc181c6df23e0ee3008a286d7183624c98c5d80c62a3b9231,
        192'h1cdff5b2e556237a33ad9e29a95e40c47291641a87c75848,
        192'hdc788ac532864391c4c47e8f8d371c2937dc35f78edb67da,
        192'he065423d7ebe7dfd43faf162d1f83ea291daadca92832eee,
        192'h44bf281c7bb1869da693521bf6c88dde5d67d95d13237714,
        192'h009e7a2f9749e52e19cf1974edba221436deab08effa992e,
        192'h73473c158488ff171e69b2c10bdd09a5ffc895f1c914e239,
        192'h2a696ef6daeb54462dffbbafbac10709e08d10394c9c6e5a,
        192'h805ef75b6d60e0984a8b932298f6fde8d7bee78d05f80f72,
        192'h65a24c42bc3d0c33f4073dd949b0ac0b84ea03751e6696db,
        192'h8ad203c36505006d639afdaa9a7cbd1e00866c5e3be967c9,
        192'h9a41bebede2537b75ad65015a541ed4d1c0af5a58f4e5007,
        192'h06fa51769fbfafdb6e4f71a47854bc2415855ed6a02b99f5,
        192'heda3263d2de5b740c91cf2fd6dd8a7cf81b8487c4eaeaa26,
        192'he82618a9b106a6424b8ded1f85baf6d70e890e84200d38d0,
        192'hd3d77b83bf6d9538184d0253e032fdc7774f9e168a600558,
        192'h43bf904602c91bd6f120c809a5ced6caf05ed1e37ae761df,
        192'h211e2f0cd6fa6253c52403944fa1d8139a3c2eb8a2483f26,
        192'h55e132d69fb349e87c86da8b8a8f68bf09254ab64a0ea8aa,
        192'h554861d280b0b340b10c17d50f288d99eb5e3a15977bd09a,
        192'hf4b62ee5534a2ac2c87a0044b91daa084a2ad0b96bcbd398,
        192'h29b9965ff9f273f7bf960627d4839752bbdde4fefc33e993,
        192'h315dcf4bcba2fcaee16140abcdf54fe149c0e38d19d77a30,
        192'hcc33234548ef37ecc0be95a07f286e6853b6bbc4d065dcbb,
        192'h65f1263de4c05585c127c2deb89956544d948675ef2e0b68,
        192'h12a31c778c1061f0d7a3212b41589d42b3d0c198d5fcdb28,
        192'h930ff2a1acbba12e4ecd9a7fc347b5ea3ba942c2bbd569b0,
        192'h260dce147a8543c5f4129d7cbd1f7c7fe7cd2522a57a1a28,
        192'h152ece0fc9e28b225a24786d370135b4dc9ff7efe5584b4f,
        192'h5b9dc332a71337a363dfb518bb42e068dc13a186a1b88fcc,
        192'ha5fcb670fa84ffe8e5510566c1bea817ebd09d7394de6223,
        192'h00b3f9d584fd364dba563c9e1a269e5dbf06e2769747663a,
        192'h157fe978e05ed9cc04ce2f949a66243b5f71db17c498863d,
        192'hb2941a30a90effb1bde24df6e5046970e583b6918a7271db,
        192'h528595379471b2d69647c9c050804a9536f1fd574d07a182,
        192'h92fecfe48a3c425b83f5044d321c4bbec470e8b0f774e08e,
        192'h0952da7fa17ddc8b0c5df107e02446263a128afdc2c0bdfc,
        192'h4c81b52a74f2e4f21bf51ab90e13ba8ca03115314a034725,
        192'h6bc9e6c202439c4da62f0d57f83a7fc6c292bd0f76784b6f,
        192'hbcb85db8b0fcf25496cad655a9d2696a1b3706b5ae7a5cb1,
        192'h2e94e9ef75f2335d45dd559cc839ed9403a6ea587ff57fdf,
        192'hc7f73c35ea4d4fefcd992eca292f08e8b185a82181cfc2ae,
        192'h4a387542ed3c8e46a7db7ce4bde1d8cdace51261dd88f538,
        192'h9d8ce22ddd7934b7533edd1f497f2964941b950fd2d8d1b6,
        192'h23f061d73940f46a522543923845ffa9f16e3e429c0892a1,
        192'h76cba787e6344657c89ba8eb0468bb613dddcbfadd46d701,
        192'h3f3c98c07ac799d8eb2bdc744ec2956df1e369f88300a54f,
        192'h9adbf56dba6ff88310a31037852f432a4b0f3dcfb6db178d,
        192'h7890aef8e263a6a4a4178bd64f07ded891ba233568381912,
        192'hcfeb5a8f4171c32187ac29be15d8b44b0df6e77ced6e41aa,
        192'ha89d78b3ca6224f91d8dcd9cc93e68a622f658b288eacb19,
        192'h4d5a4b8e35d69dcbcfc59e5079c08974d536a0bc2a4993b2,
        192'hd69bc4915e5718ed7a13f6871afcf4ad5d3e0c5aec7acbf3,
        192'h251d58eb11c84ea0b7ef58adf0567a30fec4ca982de268aa,
        192'hfb8924c35361adae6a357b9b552a2ba0d3077dcf94e0b0a6,
        192'h746949e61c53b553a9edf3b7fc613bebc15ec32c0747cfb5,
        192'h49a1cd0dc719af356e409e767b1b38d401ccfa06cd555b00,
        192'hc19e44190c4953c6c2577ef7f9449088accba143797f8411,
        192'h54f2f480278e5bcd5bcb8b22b1129f307d493121e2449a87,
        192'hc02a5e094d3a295f3114ab41288c9edecfb5b8c680aa5ee6,
        192'h8c160380c21cd21fff98a6c4e764132ffbc7a362b589026e,
        192'he9cba8764dbcb4b9f960e92ec091f157358017bdbe49db86,
        192'h796cc761f9ae87e61091c413022462c0ec5ce047d486f8ee,
        192'hd83ab17ee70a6ac3732ed6c5aa4a726805c29a1466b254d6,
        192'hfb9cd8807a15a8c2e722a2a3c3c4bac365bea0720bfb3dce
    };
    
    // DUT signals
    reg clk = 0;
    reg rst;
    reg enable;
    wire [48 * streams - 1 : 0] result;
    
    // flag to stop simulation
    integer run = 1;
    
    // error counter
    integer errors = 0;
    
    // DUT
    xormix48 #(
        .streams(streams)
    ) inst_xormix (
        .clk(clk),
        .rst(rst),
        .seed_x(seed_x),
        .seed_y(seed_y),
        .enable(enable),
        .result(result)
    );
    
    // clock process
    initial begin
        while (run == 1) begin
            clk = 1'b1;
            #5;
            clk = 1'b0;
            #5;
        end
    end
    
    integer i;
    
    // input/output process
    initial begin
        @(posedge clk);
        rst <= 1'b1;
        enable <= 1'b0;
        @(posedge clk);
        rst <= 1'b0;
        enable <= 1'b1;
        for (i = 0; i < results; i = i + 1) begin
            @(posedge clk);
            if (result !== ref_result[48 * streams * i +: 48 * streams]) begin
                $display("Incorrect result for i=%d", i);
                errors = errors + 1;
            end
        end
        $display("Test complete, number of errors: %d", errors);
        run <= 0;
    end
    
endmodule

