# Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
# Available under the MIT License - see LICENSE.txt for details.

import io
import numpy
import numpy.linalg
import random
import sys
from pathlib import Path

RANDOM_SEED = 0x2eea002f78f5a75e
START_MARKER = '// Test vectors generated by `testvec_matrix_power.py`.'
END_MARKER = '// End of test vectors.'

def reset_random():
	random.seed(RANDOM_SEED)

reset_random()

def print_array(name, n, words, cols, f=sys.stdout):
	limbs = (n + 63) // 64
	nl = n // limbs
	nt = 1 << (nl - 1).bit_length()
	ml = (1 << nl) - 1
	values = []
	for word in words:
		for limb in range(limbs):
			value = (word >> (limb * nl)) & ml
			chars = nl // 4
			values.append(f'UINT{nt}_C(0x{value:0{chars}x})')
	print(name + ' = {', file=f)
	for i in range(0, len(values), cols):
		print('\t' + ', '.join(values[i : i + cols]) + ',', file=f)
	print('};', file=f)

def print_test(n, f=sys.stdout):
	limbs = (n + 63) // 64
	nl = n // limbs
	#matrix = matrices[n]
	power = random.getrandbits(n)
	matrix_input = numpy.array([[random.getrandbits(1) for j in range(n)] for i in range(n)], dtype=numpy.uint8)
	matrix_output = numpy.linalg.matrix_power(matrix_input, power) & 1
	matrix_input2 = [sum(int(matrix_input[i, jj * nl + j]) << i for i in range(n)) for j in range(nl) for jj in range(limbs)]
	matrix_output2 = [sum(int(matrix_output[i, jj * nl + j]) << i for i in range(n)) for j in range(nl) for jj in range(limbs)]
	print_array(f'static const xormix{n}::word_t matrix_power{n}', n, [power], 4, f)
	print_array(f'static const xormix{n}::matrix_t matrix_power_input{n}', n, matrix_input2, 4, f)
	print_array(f'static const xormix{n}::matrix_t matrix_power_output{n}', n, matrix_output2, 4, f)
	print(file=f)

def generate_tests():
	reset_random()
	f = io.StringIO()
	for n in [16, 24, 32, 48, 64, 96, 128]:
		print_test(n, f=f)
	return f.getvalue()

def update_marked_file(path, generated):
	text = path.read_text()
	start = text.find(START_MARKER)
	if start == -1:
		return False
	end = text.find(END_MARKER, start)
	if end == -1:
		return False
	start_line_end = text.find('\n', start)
	if start_line_end == -1:
		return False
	replacement = text[:start_line_end + 1] + '\n' + generated.rstrip() + '\n\n' + text[end:]
	if replacement != text:
		path.write_text(replacement)
	return True

if __name__ == '__main__':
	generated = generate_tests()
	target = Path(__file__).resolve().parents[2] / 'cpp' / 'test' / 'test_matrix_power.cpp'
	if not update_marked_file(target, generated):
		print(generated, end='')
