# Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
# Available under the MIT License - see LICENSE.txt for details.

import io
import random
import sys
from pathlib import Path

RANDOM_SEED = 0xd033d34c10ffceb8
START_MARKER = '// Test vectors generated by `testvec_divide_period.py`.'
END_MARKER = '// End of test vectors.'

test_divisions = 20

def reset_random():
	random.seed(RANDOM_SEED)

reset_random()

def print_array(name, n, words, cols, f=sys.stdout):
	limbs = (n + 63) // 64
	nl = n // limbs
	nt = 1 << (nl - 1).bit_length()
	ml = (1 << nl) - 1
	values = []
	for word in words:
		for limb in range(limbs):
			value = (word >> (limb * nl)) & ml
			chars = nl // 4
			values.append(f'UINT{nt}_C(0x{value:0{chars}x})')
	print(name + ' = {', file=f)
	for i in range(0, len(values), cols):
		print('\t' + ', '.join(values[i : i + cols]) + ',', file=f)
	print('};', file=f)

def print_test(n, f=sys.stdout):
	divide_period_input = [random.randint(1, 2**(min(n, 32) * i // test_divisions + 1) - 1) for i in range(test_divisions)]
	divide_period_output = [(2**n - 1) // div for div in divide_period_input]
	print_array(f'static const size_t divide_period_input{n}[TEST_DIVISIONS]', min(n, 32), divide_period_input, 4, f)
	print_array(f'static const xormix{n}::word_t divide_period_output{n}[TEST_DIVISIONS]', n, divide_period_output, 4, f)
	print(file=f)

def generate_tests():
	reset_random()
	f = io.StringIO()
	for n in [16, 24, 32, 48, 64, 96, 128]:
		print_test(n, f=f)
	return f.getvalue()

def update_marked_file(path, generated):
	text = path.read_text()
	start = text.find(START_MARKER)
	if start == -1:
		return False
	end = text.find(END_MARKER, start)
	if end == -1:
		return False
	start_line_end = text.find('\n', start)
	if start_line_end == -1:
		return False
	replacement = text[:start_line_end + 1] + '\n' + generated.rstrip() + '\n\n' + text[end:]
	if replacement != text:
		path.write_text(replacement)
	return True

if __name__ == '__main__':
	generated = generate_tests()
	target = Path(__file__).resolve().parents[2] / 'cpp' / 'test' / 'test_divide_period.cpp'
	if not update_marked_file(target, generated):
		print(generated, end='')
