# Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
# Available under the MIT License - see LICENSE.txt for details.

import io
import random
import sys
from pathlib import Path

from xormix_all import modules

RANDOM_SEED = 0x3f10d933ecfc0a73
START_MARKER = '// Test vectors generated by `testvec_output.py`.'
END_MARKER = '// End of test vectors.'

def reset_random():
	random.seed(RANDOM_SEED)

reset_random()

def print_array(name, n, words, cols, f=sys.stdout):
	limbs = (n + 63) // 64
	nl = n // limbs
	nt = 1 << (nl - 1).bit_length()
	ml = (1 << nl) - 1
	values = []
	for word in words:
		for limb in range(limbs):
			value = (word >> (limb * nl)) & ml
			chars = nl // 4
			values.append(f'UINT{nt}_C(0x{value:0{chars}x})')
	print(name + ' = {', file=f)
	for i in range(0, len(values), cols):
		print('\t' + ', '.join(values[i : i + cols]) + ',', file=f)
	print('};', file=f)

def random_word_nonzero(n):
	while True:
		word = random.getrandbits(n)
		if word != 0:
			return word

def pack_words(n, words):
	word = 0
	for i, value in enumerate(words):
		word |= value << (i * n)
	return word

def generate_output(n, state, test_outputs):
	state = state.copy()
	output = []
	for i in range(test_outputs):
		modules[n].next_state(state)
		output += state
	return output

def print_test(n, test_streams=4, test_outputs=100, f=sys.stdout):
	print(f'static constexpr size_t XORMIX{n}_TEST_STREAMS = {test_streams};', file=f)
	print(f'static constexpr size_t XORMIX{n}_TEST_OUTPUTS = {test_outputs};', file=f)

	full_seed_x = random_word_nonzero(n)
	full_seed_y = [random.getrandbits(n) for i in range(test_streams)]
	full_state = modules[n].seed_full(full_seed_x, pack_words(n, full_seed_y), test_streams)
	full_output = generate_output(n, full_state, test_outputs)
	print_array(f'static const xormix{n}::word_t xormix{n}_full_seeds[XORMIX{n}_TEST_STREAMS + 1]', n, [full_seed_x] + full_seed_y, 5, f)
	print_array(f'static const xormix{n}::word_t xormix{n}_full_output[XORMIX{n}_TEST_OUTPUTS][XORMIX{n}_TEST_STREAMS + 1]', n, full_output, 5, f)

	simple_seed_x = random_word_nonzero(n)
	simple_seed_y = random.getrandbits(n)
	simple_output = generate_output(n, modules[n].seed_simple(simple_seed_x, simple_seed_y, test_streams), test_outputs)
	print_array(f'static const xormix{n}::word_t xormix{n}_simple_seeds[2]', n, [simple_seed_x, simple_seed_y], 5, f)
	print_array(f'static const xormix{n}::word_t xormix{n}_simple_output[XORMIX{n}_TEST_OUTPUTS][XORMIX{n}_TEST_STREAMS + 1]', n, simple_output, 5, f)

	fast_seed_x = random_word_nonzero(n)
	fast_seed_y = random.getrandbits(n)
	fast_output = generate_output(n, modules[n].seed_fast(fast_seed_x, fast_seed_y, test_streams), test_outputs)
	print_array(f'static const xormix{n}::word_t xormix{n}_fast_seeds[2]', n, [fast_seed_x, fast_seed_y], 5, f)
	print_array(f'static const xormix{n}::word_t xormix{n}_fast_output[XORMIX{n}_TEST_OUTPUTS][XORMIX{n}_TEST_STREAMS + 1]', n, fast_output, 5, f)
	print(file=f)

def generate_tests(configs = None):
	reset_random()
	f = io.StringIO()
	if configs is None:
		configs = [(n, 4, 100) for n in [16, 24, 32, 48, 64, 96, 128]]
	for n, test_streams, test_outputs in configs:
		print_test(n, test_streams=test_streams, test_outputs=test_outputs, f=f)
	return f.getvalue()

def update_marked_file(path, generated, start_marker=START_MARKER, end_marker=END_MARKER):
	text = path.read_text()
	start = text.find(start_marker)
	if start == -1:
		return False
	end = text.find(end_marker, start)
	if end == -1:
		return False
	start_line_end = text.find('\n', start)
	if start_line_end == -1:
		return False
	replacement = text[:start_line_end + 1] + '\n' + generated.rstrip() + '\n\n' + text[end:]
	if replacement != text:
		path.write_text(replacement)
	return True

if __name__ == '__main__':
	generated = generate_tests()
	target = Path(__file__).resolve().parents[2] / 'cpp' / 'test' / 'test_output.cpp'
	if not update_marked_file(target, generated):
		print(generated, end='')
