# Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
# Available under the MIT License - see LICENSE.txt for details.

import testvec_output

START_MARKER = '// Test vectors generated by `testvec_output_wide.py`.'
END_MARKER = '// End of test vectors.'

if __name__ == '__main__':
	configs = [(n, n - 3, 384 // n) for n in [16, 24, 32, 48, 64, 96, 128]]
	generated = testvec_output.generate_tests(configs)
	target = testvec_output.Path(__file__).resolve().parents[2] / 'cpp' / 'test' / 'test_output_wide.cpp'
	if not testvec_output.update_marked_file(target, generated, START_MARKER, END_MARKER):
		print(generated, end='')
