// Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
// Available under the MIT License - see LICENSE.txt for details.

// This file was generated by `generate_verilog.py`.

module xormix64
    #(
        parameter streams = 1
    )
    (
        
        // clock and synchronous reset
        input wire clk,
        input wire rst,
        
        // configuration
        input wire [63 : 0] seed_x,
        input wire [64 * streams - 1 : 0] seed_y,
        
        // random number generator
        input wire enable,
        output wire [64 * streams - 1 : 0] result
        
    );
    
    localparam [64 * 64 - 1 : 0] salts = {
        64'he9602cb6280a6c70, 64'he3bd59c3b7844bc4, 64'hf811709d805968db, 64'h42a68068988aff0c,
        64'hc5041c150065d8fd, 64'h135e1971c5db62b7, 64'h71aaacdba83328de, 64'h14eccb6a88a0129e,
        64'h0adeb7af980adf73, 64'hcf1f611a8269bc91, 64'hdda19468d60247e6, 64'ha35d4d739948bace,
        64'h61c2af10615a09fb, 64'heaebc14b790da4b9, 64'h2ff27333a309bbbc, 64'h1388ee338164ea29,
        64'h77ecc3481691cd65, 64'h590494397519cd48, 64'hb3bc2c1931d5afe6, 64'h6863f70a8cc13391,
        64'h5c72e28f77c7ab3d, 64'h993e260d3c6f44bc, 64'hadbcae73ac34dd49, 64'h68d7594964f92460,
        64'ha2e9693598d4d120, 64'hfc666ffe8b3ee689, 64'h42a866fb536b5c24, 64'h282dcf755931c792,
        64'h6f801ac1a01937d3, 64'h6026a67855446ab6, 64'h635aa20bf255c061, 64'h3bebfb323f75041e,
        64'hd79394eb53e8e614, 64'h3e2a049598688d41, 64'hcca5d6d4ad8ff5e6, 64'ha47463136a589763,
        64'h136354a988e7dc44, 64'h9ae49767ed2aac9d, 64'h344a280b81b3dc59, 64'h0fca61766c25a956,
        64'h3f8fae1df7b5284f, 64'h3aca5c28507a9812, 64'h05fa834a446f5780, 64'h9819f173380f1778,
        64'h2bd0973542881c68, 64'h4711b906c747cf69, 64'he7740ee396e0303c, 64'ha8b436b35f0594b6,
        64'h63600f8ae4c7a36a, 64'h3edd68a5eb6ba2b1, 64'hdb6752d26b3e7d9a, 64'h42c3fc05de25f0c0,
        64'hbb625e1c429581e7, 64'h147610fcd384ae2a, 64'h87ce80324751b6e0, 64'hffc0742fc5f3dbe3,
        64'h8d2ef95b68e2110b, 64'h5def7160d6d4e4b9, 64'hb89b5f5e1de22367, 64'h7cb8aabfdc88b651,
        64'h6402b3d837dfb664, 64'h9384f7a0b1b8600e, 64'h254b7cacdf1f7f73, 64'h6c1f4cf86b670928
    };
    
    reg [63 : 0] r_state_x;
    reg [64 * streams - 1 : 0] r_state_y;
    
    reg [64 * streams - 1 : 0] v_state_y1;
    reg [64 * streams - 1 : 0] v_state_y2;
    
    reg [63 : 0] v_mixin;
    reg [63 : 0] v_mixup;
    reg [63 : 0] v_res;
    
    integer i;
    
    assign result = r_state_y;
    
    always @(*) begin
        
        for (i = 0; i < streams; i = i + 1) begin
            v_mixin = r_state_x ^ salts[64 * i +: 64];
            v_mixup = r_state_y[64 * ((i + 1) % streams) +: 64];
            v_res[ 0] = v_mixup[ 0] ^ (v_mixup[28] & ~v_mixup[31]) ^ v_mixup[24] ^ v_mixup[30] ^ v_mixin[(i + 39) % 64];
            v_res[ 1] = v_mixup[ 1] ^ (v_mixup[29] & ~v_mixup[32]) ^ v_mixup[25] ^ v_mixup[31] ^ v_mixin[(i + 11) % 64];
            v_res[ 2] = v_mixup[ 2] ^ (v_mixup[30] & ~v_mixup[33]) ^ v_mixup[26] ^ v_mixup[32] ^ v_mixin[(i + 51) % 64];
            v_res[ 3] = v_mixup[ 3] ^ (v_mixup[31] & ~v_mixup[34]) ^ v_mixup[27] ^ v_mixup[33] ^ v_mixin[(i + 53) % 64];
            v_res[ 4] = v_mixup[ 4] ^ (v_mixup[32] & ~v_mixup[35]) ^ v_mixup[28] ^ v_mixup[34] ^ v_mixin[(i + 61) % 64];
            v_res[ 5] = v_mixup[ 5] ^ (v_mixup[33] & ~v_mixup[36]) ^ v_mixup[29] ^ v_mixup[35] ^ v_mixin[(i + 31) % 64];
            v_res[ 6] = v_mixup[ 6] ^ (v_mixup[34] & ~v_mixup[37]) ^ v_mixup[30] ^ v_mixup[36] ^ v_mixin[(i + 29) % 64];
            v_res[ 7] = v_mixup[ 7] ^ (v_mixup[35] & ~v_mixup[38]) ^ v_mixup[31] ^ v_mixup[37] ^ v_mixin[(i + 27) % 64];
            v_res[ 8] = v_mixup[ 8] ^ (v_mixup[36] & ~v_mixup[39]) ^ v_mixup[32] ^ v_mixup[38] ^ v_mixin[(i + 12) % 64];
            v_res[ 9] = v_mixup[ 9] ^ (v_mixup[37] & ~v_mixup[40]) ^ v_mixup[33] ^ v_mixup[39] ^ v_mixin[(i + 57) % 64];
            v_res[10] = v_mixup[10] ^ (v_mixup[38] & ~v_mixup[41]) ^ v_mixup[34] ^ v_mixup[40] ^ v_mixin[(i + 43) % 64];
            v_res[11] = v_mixup[11] ^ (v_mixup[39] & ~v_mixup[42]) ^ v_mixup[35] ^ v_mixup[41] ^ v_mixin[(i + 56) % 64];
            v_res[12] = v_mixup[12] ^ (v_mixup[40] & ~v_mixup[43]) ^ v_mixup[36] ^ v_mixup[42] ^ v_mixin[(i + 42) % 64];
            v_res[13] = v_mixup[13] ^ (v_mixup[41] & ~v_mixup[44]) ^ v_mixup[37] ^ v_mixup[43] ^ v_mixin[(i +  2) % 64];
            v_res[14] = v_mixup[14] ^ (v_mixup[42] & ~v_mixup[45]) ^ v_mixup[38] ^ v_mixup[44] ^ v_mixin[(i + 26) % 64];
            v_res[15] = v_mixup[15] ^ (v_mixup[43] & ~v_mixup[46]) ^ v_mixup[39] ^ v_mixup[45] ^ v_mixin[(i + 37) % 64];
            v_res[16] = v_mixup[16] ^ (v_mixup[44] & ~v_mixup[47]) ^ v_mixup[40] ^ v_mixup[46] ^ v_mixin[(i + 41) % 64];
            v_res[17] = v_mixup[17] ^ (v_mixup[45] & ~v_mixup[48]) ^ v_mixup[41] ^ v_mixup[47] ^ v_mixin[(i + 10) % 64];
            v_res[18] = v_mixup[18] ^ (v_mixup[46] & ~v_mixup[49]) ^ v_mixup[42] ^ v_mixup[48] ^ v_mixin[(i + 20) % 64];
            v_res[19] = v_mixup[19] ^ (v_mixup[47] & ~v_mixup[50]) ^ v_mixup[43] ^ v_mixup[49] ^ v_mixin[(i + 44) % 64];
            v_res[20] = v_mixup[20] ^ (v_mixup[48] & ~v_mixup[51]) ^ v_mixup[44] ^ v_mixup[50] ^ v_mixin[(i +  7) % 64];
            v_res[21] = v_mixup[21] ^ (v_mixup[49] & ~v_mixup[52]) ^ v_mixup[45] ^ v_mixup[51] ^ v_mixin[(i + 28) % 64];
            v_res[22] = v_mixup[22] ^ (v_mixup[50] & ~v_mixup[53]) ^ v_mixup[46] ^ v_mixup[52] ^ v_mixin[(i + 13) % 64];
            v_res[23] = v_mixup[23] ^ (v_mixup[51] & ~v_mixup[54]) ^ v_mixup[47] ^ v_mixup[53] ^ v_mixin[(i +  9) % 64];
            v_res[24] = v_mixup[24] ^ (v_mixup[52] & ~v_mixup[55]) ^ v_mixup[48] ^ v_mixup[54] ^ v_mixin[(i + 25) % 64];
            v_res[25] = v_mixup[25] ^ (v_mixup[53] & ~v_mixup[56]) ^ v_mixup[49] ^ v_mixup[55] ^ v_mixin[(i + 32) % 64];
            v_res[26] = v_mixup[26] ^ (v_mixup[54] & ~v_mixup[57]) ^ v_mixup[50] ^ v_mixup[56] ^ v_mixin[(i + 52) % 64];
            v_res[27] = v_mixup[27] ^ (v_mixup[55] & ~v_mixup[58]) ^ v_mixup[51] ^ v_mixup[57] ^ v_mixin[(i + 14) % 64];
            v_res[28] = v_mixup[28] ^ (v_mixup[56] & ~v_mixup[59]) ^ v_mixup[52] ^ v_mixup[58] ^ v_mixin[(i + 19) % 64];
            v_res[29] = v_mixup[29] ^ (v_mixup[57] & ~v_mixup[60]) ^ v_mixup[53] ^ v_mixup[59] ^ v_mixin[(i + 60) % 64];
            v_res[30] = v_mixup[30] ^ (v_mixup[58] & ~v_mixup[61]) ^ v_mixup[54] ^ v_mixup[60] ^ v_mixin[(i + 48) % 64];
            v_res[31] = v_mixup[31] ^ (v_mixup[59] & ~v_mixup[62]) ^ v_mixup[55] ^ v_mixup[61] ^ v_mixin[(i + 49) % 64];
            v_state_y1[64 * i +: 64] = {v_res, r_state_y[64 * i + 32 +: 32]};
        end
        
        for (i = 0; i < streams; i = i + 1) begin
            v_mixin = r_state_x ^ salts[64 * i +: 64];
            v_mixup = v_state_y1[64 * ((i + 1) % streams) +: 64];
            v_res[ 0] = v_mixup[ 0] ^ (v_mixup[28] & ~v_mixup[31]) ^ v_mixup[24] ^ v_mixup[30] ^ v_mixin[(i +  5) % 64];
            v_res[ 1] = v_mixup[ 1] ^ (v_mixup[29] & ~v_mixup[32]) ^ v_mixup[25] ^ v_mixup[31] ^ v_mixin[(i + 36) % 64];
            v_res[ 2] = v_mixup[ 2] ^ (v_mixup[30] & ~v_mixup[33]) ^ v_mixup[26] ^ v_mixup[32] ^ v_mixin[(i +  0) % 64];
            v_res[ 3] = v_mixup[ 3] ^ (v_mixup[31] & ~v_mixup[34]) ^ v_mixup[27] ^ v_mixup[33] ^ v_mixin[(i +  3) % 64];
            v_res[ 4] = v_mixup[ 4] ^ (v_mixup[32] & ~v_mixup[35]) ^ v_mixup[28] ^ v_mixup[34] ^ v_mixin[(i + 58) % 64];
            v_res[ 5] = v_mixup[ 5] ^ (v_mixup[33] & ~v_mixup[36]) ^ v_mixup[29] ^ v_mixup[35] ^ v_mixin[(i + 22) % 64];
            v_res[ 6] = v_mixup[ 6] ^ (v_mixup[34] & ~v_mixup[37]) ^ v_mixup[30] ^ v_mixup[36] ^ v_mixin[(i + 35) % 64];
            v_res[ 7] = v_mixup[ 7] ^ (v_mixup[35] & ~v_mixup[38]) ^ v_mixup[31] ^ v_mixup[37] ^ v_mixin[(i + 21) % 64];
            v_res[ 8] = v_mixup[ 8] ^ (v_mixup[36] & ~v_mixup[39]) ^ v_mixup[32] ^ v_mixup[38] ^ v_mixin[(i + 16) % 64];
            v_res[ 9] = v_mixup[ 9] ^ (v_mixup[37] & ~v_mixup[40]) ^ v_mixup[33] ^ v_mixup[39] ^ v_mixin[(i + 30) % 64];
            v_res[10] = v_mixup[10] ^ (v_mixup[38] & ~v_mixup[41]) ^ v_mixup[34] ^ v_mixup[40] ^ v_mixin[(i + 34) % 64];
            v_res[11] = v_mixup[11] ^ (v_mixup[39] & ~v_mixup[42]) ^ v_mixup[35] ^ v_mixup[41] ^ v_mixin[(i + 63) % 64];
            v_res[12] = v_mixup[12] ^ (v_mixup[40] & ~v_mixup[43]) ^ v_mixup[36] ^ v_mixup[42] ^ v_mixin[(i +  8) % 64];
            v_res[13] = v_mixup[13] ^ (v_mixup[41] & ~v_mixup[44]) ^ v_mixup[37] ^ v_mixup[43] ^ v_mixin[(i + 17) % 64];
            v_res[14] = v_mixup[14] ^ (v_mixup[42] & ~v_mixup[45]) ^ v_mixup[38] ^ v_mixup[44] ^ v_mixin[(i + 24) % 64];
            v_res[15] = v_mixup[15] ^ (v_mixup[43] & ~v_mixup[46]) ^ v_mixup[39] ^ v_mixup[45] ^ v_mixin[(i + 54) % 64];
            v_res[16] = v_mixup[16] ^ (v_mixup[44] & ~v_mixup[47]) ^ v_mixup[40] ^ v_mixup[46] ^ v_mixin[(i + 18) % 64];
            v_res[17] = v_mixup[17] ^ (v_mixup[45] & ~v_mixup[48]) ^ v_mixup[41] ^ v_mixup[47] ^ v_mixin[(i + 50) % 64];
            v_res[18] = v_mixup[18] ^ (v_mixup[46] & ~v_mixup[49]) ^ v_mixup[42] ^ v_mixup[48] ^ v_mixin[(i + 45) % 64];
            v_res[19] = v_mixup[19] ^ (v_mixup[47] & ~v_mixup[50]) ^ v_mixup[43] ^ v_mixup[49] ^ v_mixin[(i +  6) % 64];
            v_res[20] = v_mixup[20] ^ (v_mixup[48] & ~v_mixup[51]) ^ v_mixup[44] ^ v_mixup[50] ^ v_mixin[(i + 46) % 64];
            v_res[21] = v_mixup[21] ^ (v_mixup[49] & ~v_mixup[52]) ^ v_mixup[45] ^ v_mixup[51] ^ v_mixin[(i + 33) % 64];
            v_res[22] = v_mixup[22] ^ (v_mixup[50] & ~v_mixup[53]) ^ v_mixup[46] ^ v_mixup[52] ^ v_mixin[(i + 23) % 64];
            v_res[23] = v_mixup[23] ^ (v_mixup[51] & ~v_mixup[54]) ^ v_mixup[47] ^ v_mixup[53] ^ v_mixin[(i + 62) % 64];
            v_res[24] = v_mixup[24] ^ (v_mixup[52] & ~v_mixup[55]) ^ v_mixup[48] ^ v_mixup[54] ^ v_mixin[(i + 15) % 64];
            v_res[25] = v_mixup[25] ^ (v_mixup[53] & ~v_mixup[56]) ^ v_mixup[49] ^ v_mixup[55] ^ v_mixin[(i + 59) % 64];
            v_res[26] = v_mixup[26] ^ (v_mixup[54] & ~v_mixup[57]) ^ v_mixup[50] ^ v_mixup[56] ^ v_mixin[(i + 55) % 64];
            v_res[27] = v_mixup[27] ^ (v_mixup[55] & ~v_mixup[58]) ^ v_mixup[51] ^ v_mixup[57] ^ v_mixin[(i + 38) % 64];
            v_res[28] = v_mixup[28] ^ (v_mixup[56] & ~v_mixup[59]) ^ v_mixup[52] ^ v_mixup[58] ^ v_mixin[(i + 40) % 64];
            v_res[29] = v_mixup[29] ^ (v_mixup[57] & ~v_mixup[60]) ^ v_mixup[53] ^ v_mixup[59] ^ v_mixin[(i +  1) % 64];
            v_res[30] = v_mixup[30] ^ (v_mixup[58] & ~v_mixup[61]) ^ v_mixup[54] ^ v_mixup[60] ^ v_mixin[(i +  4) % 64];
            v_res[31] = v_mixup[31] ^ (v_mixup[59] & ~v_mixup[62]) ^ v_mixup[55] ^ v_mixup[61] ^ v_mixin[(i + 47) % 64];
            v_state_y2[64 * i +: 64] = {v_res, v_state_y1[64 * i + 32 +: 32]};
        end
        
    end
    
    always @(posedge clk) begin
        if (rst == 1'b1) begin
            
            r_state_x <= seed_x;
            r_state_y <= seed_y;
            
        end else if (enable == 1'b1) begin
            
            r_state_x[ 0] <= r_state_x[56] ^ r_state_x[40] ^ r_state_x[59] ^ r_state_x[ 0] ^ r_state_x[27];
            r_state_x[ 1] <= r_state_x[49] ^ r_state_x[48] ^ r_state_x[ 4] ^ r_state_x[39] ^ r_state_x[10] ^ r_state_x[31];
            r_state_x[ 2] <= r_state_x[15] ^ r_state_x[35] ^ r_state_x[32] ^ r_state_x[ 7] ^ r_state_x[23];
            r_state_x[ 3] <= r_state_x[14] ^ r_state_x[ 3] ^ r_state_x[37] ^ r_state_x[49] ^ r_state_x[28] ^ r_state_x[61];
            r_state_x[ 4] <= r_state_x[48] ^ r_state_x[18] ^ r_state_x[59] ^ r_state_x[29] ^ r_state_x[25];
            r_state_x[ 5] <= r_state_x[ 1] ^ r_state_x[44] ^ r_state_x[18] ^ r_state_x[19] ^ r_state_x[ 6] ^ r_state_x[ 2];
            r_state_x[ 6] <= r_state_x[41] ^ r_state_x[39] ^ r_state_x[15] ^ r_state_x[14] ^ r_state_x[33];
            r_state_x[ 7] <= r_state_x[59] ^ r_state_x[40] ^ r_state_x[32] ^ r_state_x[27] ^ r_state_x[63] ^ r_state_x[50];
            r_state_x[ 8] <= r_state_x[10] ^ r_state_x[37] ^ r_state_x[17] ^ r_state_x[ 8] ^ r_state_x[21];
            r_state_x[ 9] <= r_state_x[47] ^ r_state_x[30] ^ r_state_x[11] ^ r_state_x[25] ^ r_state_x[16] ^ r_state_x[58];
            r_state_x[10] <= r_state_x[36] ^ r_state_x[60] ^ r_state_x[58] ^ r_state_x[23] ^ r_state_x[25];
            r_state_x[11] <= r_state_x[47] ^ r_state_x[21] ^ r_state_x[46] ^ r_state_x[ 5] ^ r_state_x[29] ^ r_state_x[32];
            r_state_x[12] <= r_state_x[ 7] ^ r_state_x[63] ^ r_state_x[44] ^ r_state_x[19] ^ r_state_x[60];
            r_state_x[13] <= r_state_x[22] ^ r_state_x[52] ^ r_state_x[49] ^ r_state_x[18] ^ r_state_x[15] ^ r_state_x[ 3];
            r_state_x[14] <= r_state_x[32] ^ r_state_x[46] ^ r_state_x[ 5] ^ r_state_x[ 6] ^ r_state_x[31];
            r_state_x[15] <= r_state_x[42] ^ r_state_x[33] ^ r_state_x[16] ^ r_state_x[ 1] ^ r_state_x[21] ^ r_state_x[ 6];
            r_state_x[16] <= r_state_x[34] ^ r_state_x[11] ^ r_state_x[18] ^ r_state_x[55] ^ r_state_x[12];
            r_state_x[17] <= r_state_x[41] ^ r_state_x[43] ^ r_state_x[10] ^ r_state_x[47] ^ r_state_x[57] ^ r_state_x[28];
            r_state_x[18] <= r_state_x[31] ^ r_state_x[38] ^ r_state_x[13] ^ r_state_x[32] ^ r_state_x[48];
            r_state_x[19] <= r_state_x[ 8] ^ r_state_x[ 9] ^ r_state_x[36] ^ r_state_x[62] ^ r_state_x[ 1] ^ r_state_x[42];
            r_state_x[20] <= r_state_x[45] ^ r_state_x[ 3] ^ r_state_x[57] ^ r_state_x[ 4] ^ r_state_x[59];
            r_state_x[21] <= r_state_x[34] ^ r_state_x[27] ^ r_state_x[48] ^ r_state_x[39] ^ r_state_x[41] ^ r_state_x[12];
            r_state_x[22] <= r_state_x[40] ^ r_state_x[17] ^ r_state_x[36] ^ r_state_x[54] ^ r_state_x[62];
            r_state_x[23] <= r_state_x[13] ^ r_state_x[ 9] ^ r_state_x[45] ^ r_state_x[25] ^ r_state_x[28] ^ r_state_x[42];
            r_state_x[24] <= r_state_x[21] ^ r_state_x[17] ^ r_state_x[54] ^ r_state_x[60] ^ r_state_x[ 0];
            r_state_x[25] <= r_state_x[ 8] ^ r_state_x[48] ^ r_state_x[47] ^ r_state_x[40] ^ r_state_x[ 4] ^ r_state_x[19];
            r_state_x[26] <= r_state_x[22] ^ r_state_x[25] ^ r_state_x[42] ^ r_state_x[37] ^ r_state_x[32];
            r_state_x[27] <= r_state_x[ 6] ^ r_state_x[38] ^ r_state_x[26] ^ r_state_x[50] ^ r_state_x[49] ^ r_state_x[41];
            r_state_x[28] <= r_state_x[26] ^ r_state_x[51] ^ r_state_x[62] ^ r_state_x[24] ^ r_state_x[15];
            r_state_x[29] <= r_state_x[31] ^ r_state_x[ 6] ^ r_state_x[54] ^ r_state_x[56] ^ r_state_x[58] ^ r_state_x[29];
            r_state_x[30] <= r_state_x[20] ^ r_state_x[63] ^ r_state_x[ 2] ^ r_state_x[22] ^ r_state_x[ 9];
            r_state_x[31] <= r_state_x[ 5] ^ r_state_x[14] ^ r_state_x[42] ^ r_state_x[56] ^ r_state_x[12] ^ r_state_x[15];
            r_state_x[32] <= r_state_x[ 8] ^ r_state_x[20] ^ r_state_x[51] ^ r_state_x[12] ^ r_state_x[53];
            r_state_x[33] <= r_state_x[52] ^ r_state_x[43] ^ r_state_x[ 0] ^ r_state_x[11] ^ r_state_x[46] ^ r_state_x[23];
            r_state_x[34] <= r_state_x[12] ^ r_state_x[20] ^ r_state_x[38] ^ r_state_x[16] ^ r_state_x[44];
            r_state_x[35] <= r_state_x[28] ^ r_state_x[ 3] ^ r_state_x[59] ^ r_state_x[53] ^ r_state_x[38] ^ r_state_x[21];
            r_state_x[36] <= r_state_x[10] ^ r_state_x[56] ^ r_state_x[30] ^ r_state_x[57] ^ r_state_x[38];
            r_state_x[37] <= r_state_x[47] ^ r_state_x[50] ^ r_state_x[ 6] ^ r_state_x[54] ^ r_state_x[ 4] ^ r_state_x[49];
            r_state_x[38] <= r_state_x[22] ^ r_state_x[36] ^ r_state_x[ 7] ^ r_state_x[45] ^ r_state_x[37];
            r_state_x[39] <= r_state_x[46] ^ r_state_x[21] ^ r_state_x[26] ^ r_state_x[55] ^ r_state_x[58] ^ r_state_x[35];
            r_state_x[40] <= r_state_x[14] ^ r_state_x[26] ^ r_state_x[34] ^ r_state_x[33] ^ r_state_x[17];
            r_state_x[41] <= r_state_x[43] ^ r_state_x[50] ^ r_state_x[55] ^ r_state_x[58] ^ r_state_x[ 2] ^ r_state_x[ 1];
            r_state_x[42] <= r_state_x[55] ^ r_state_x[57] ^ r_state_x[33] ^ r_state_x[49] ^ r_state_x[51];
            r_state_x[43] <= r_state_x[47] ^ r_state_x[26] ^ r_state_x[22] ^ r_state_x[ 0] ^ r_state_x[35] ^ r_state_x[10];
            r_state_x[44] <= r_state_x[30] ^ r_state_x[39] ^ r_state_x[56] ^ r_state_x[57] ^ r_state_x[ 7];
            r_state_x[45] <= r_state_x[53] ^ r_state_x[24] ^ r_state_x[52] ^ r_state_x[12] ^ r_state_x[44] ^ r_state_x[36];
            r_state_x[46] <= r_state_x[ 5] ^ r_state_x[58] ^ r_state_x[52] ^ r_state_x[ 9] ^ r_state_x[20];
            r_state_x[47] <= r_state_x[ 7] ^ r_state_x[16] ^ r_state_x[62] ^ r_state_x[42] ^ r_state_x[53] ^ r_state_x[38];
            r_state_x[48] <= r_state_x[19] ^ r_state_x[28] ^ r_state_x[ 4] ^ r_state_x[27] ^ r_state_x[13];
            r_state_x[49] <= r_state_x[26] ^ r_state_x[46] ^ r_state_x[20] ^ r_state_x[27] ^ r_state_x[17] ^ r_state_x[29];
            r_state_x[50] <= r_state_x[28] ^ r_state_x[40] ^ r_state_x[14] ^ r_state_x[ 4] ^ r_state_x[63];
            r_state_x[51] <= r_state_x[ 2] ^ r_state_x[24] ^ r_state_x[61] ^ r_state_x[ 1] ^ r_state_x[ 5] ^ r_state_x[56];
            r_state_x[52] <= r_state_x[45] ^ r_state_x[23] ^ r_state_x[44] ^ r_state_x[18] ^ r_state_x[39];
            r_state_x[53] <= r_state_x[45] ^ r_state_x[40] ^ r_state_x[29] ^ r_state_x[61] ^ r_state_x[ 0] ^ r_state_x[33];
            r_state_x[54] <= r_state_x[ 7] ^ r_state_x[50] ^ r_state_x[ 5] ^ r_state_x[62] ^ r_state_x[13];
            r_state_x[55] <= r_state_x[13] ^ r_state_x[14] ^ r_state_x[61] ^ r_state_x[17] ^ r_state_x[63] ^ r_state_x[18];
            r_state_x[56] <= r_state_x[27] ^ r_state_x[34] ^ r_state_x[ 9] ^ r_state_x[24] ^ r_state_x[11];
            r_state_x[57] <= r_state_x[ 0] ^ r_state_x[19] ^ r_state_x[23] ^ r_state_x[ 7] ^ r_state_x[59] ^ r_state_x[25];
            r_state_x[58] <= r_state_x[51] ^ r_state_x[ 4] ^ r_state_x[30] ^ r_state_x[46] ^ r_state_x[61];
            r_state_x[59] <= r_state_x[11] ^ r_state_x[54] ^ r_state_x[52] ^ r_state_x[24] ^ r_state_x[60] ^ r_state_x[35];
            r_state_x[60] <= r_state_x[30] ^ r_state_x[55] ^ r_state_x[53] ^ r_state_x[16] ^ r_state_x[31];
            r_state_x[61] <= r_state_x[ 3] ^ r_state_x[33] ^ r_state_x[36] ^ r_state_x[58] ^ r_state_x[ 8] ^ r_state_x[45];
            r_state_x[62] <= r_state_x[37] ^ r_state_x[41] ^ r_state_x[62] ^ r_state_x[34] ^ r_state_x[35];
            r_state_x[63] <= r_state_x[63] ^ r_state_x[39] ^ r_state_x[22] ^ r_state_x[55] ^ r_state_x[43] ^ r_state_x[42];
            
            r_state_y <= v_state_y2;
            
        end
    end
    
endmodule

