// Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
// Available under the MIT License - see LICENSE.txt for details.

// This file was generated by `generate_verilog.py`.

module xormix48
    #(
        parameter streams = 1
    )
    (
        
        // clock and synchronous reset
        input wire clk,
        input wire rst,
        
        // configuration
        input wire [47 : 0] seed_x,
        input wire [48 * streams - 1 : 0] seed_y,
        
        // random number generator
        input wire enable,
        output wire [48 * streams - 1 : 0] result
        
    );
    
    localparam [48 * 48 - 1 : 0] salts = {
        48'h34c3236725e9, 48'h00302447d0cf, 48'h583491406df0, 48'h9379f90a2ff8,
        48'h109c81c9df19, 48'hf7c8549141c1, 48'he92ab1204c26, 48'h3e8785982f5c,
        48'h1d16c2d1672f, 48'h981e3a7298fb, 48'h8c2c614e379f, 48'h7de7947afb4b,
        48'hb8ff040d894b, 48'h93fb56272e46, 48'h6470f197fbcc, 48'h4ae1ee2f8ff1,
        48'h377cf18c8a09, 48'hd307b0424a1f, 48'hfd4ca29740b2, 48'haa5f9fc3447b,
        48'h3f0b1417a83e, 48'hd63a2e6c6b6e, 48'he6066341f129, 48'h0635bdf9a9a1,
        48'h1a4f0b78edd2, 48'h0f2cf602d40a, 48'h11f41b1ba06e, 48'hfe1e25f4f213,
        48'hc4d0b2be2d19, 48'h4db37369078b, 48'h2de1ba749c87, 48'h117087d44a4c,
        48'he182ee2c64dc, 48'h59bf4852d6de, 48'h54d0862260f6, 48'h8f8919a04ad3,
        48'h8a9ef2995097, 48'h4f2b4ee6a079, 48'h316767a3bcb6, 48'h16f61844dd41,
        48'h34504e889c4e, 48'h838aa6d68e51, 48'hc9fdd5da7238, 48'hadc3319ee962,
        48'h75cf3224f670, 48'h368fddfe10b2, 48'he3e9a7b5f00f, 48'hdc2a970723c9
    };
    
    reg [47 : 0] r_state_x;
    reg [48 * streams - 1 : 0] r_state_y;
    
    reg [48 * streams - 1 : 0] v_state_y1;
    reg [48 * streams - 1 : 0] v_state_y2;
    
    reg [47 : 0] v_mixin;
    reg [47 : 0] v_mixup;
    reg [47 : 0] v_res;
    
    integer i;
    
    assign result = r_state_y;
    
    always @(*) begin
        
        for (i = 0; i < streams; i = i + 1) begin
            v_mixin = r_state_x ^ salts[48 * i +: 48];
            v_mixup = r_state_y[48 * ((i + 1) % streams) +: 48];
            v_res[ 0] = v_mixup[ 0] ^ (v_mixup[19] & ~v_mixup[21]) ^ v_mixup[15] ^ v_mixup[22] ^ v_mixin[(i +  8) % 48];
            v_res[ 1] = v_mixup[ 1] ^ (v_mixup[20] & ~v_mixup[22]) ^ v_mixup[16] ^ v_mixup[23] ^ v_mixin[(i + 23) % 48];
            v_res[ 2] = v_mixup[ 2] ^ (v_mixup[21] & ~v_mixup[23]) ^ v_mixup[17] ^ v_mixup[24] ^ v_mixin[(i +  2) % 48];
            v_res[ 3] = v_mixup[ 3] ^ (v_mixup[22] & ~v_mixup[24]) ^ v_mixup[18] ^ v_mixup[25] ^ v_mixin[(i + 15) % 48];
            v_res[ 4] = v_mixup[ 4] ^ (v_mixup[23] & ~v_mixup[25]) ^ v_mixup[19] ^ v_mixup[26] ^ v_mixin[(i + 46) % 48];
            v_res[ 5] = v_mixup[ 5] ^ (v_mixup[24] & ~v_mixup[26]) ^ v_mixup[20] ^ v_mixup[27] ^ v_mixin[(i + 31) % 48];
            v_res[ 6] = v_mixup[ 6] ^ (v_mixup[25] & ~v_mixup[27]) ^ v_mixup[21] ^ v_mixup[28] ^ v_mixin[(i + 22) % 48];
            v_res[ 7] = v_mixup[ 7] ^ (v_mixup[26] & ~v_mixup[28]) ^ v_mixup[22] ^ v_mixup[29] ^ v_mixin[(i + 12) % 48];
            v_res[ 8] = v_mixup[ 8] ^ (v_mixup[27] & ~v_mixup[29]) ^ v_mixup[23] ^ v_mixup[30] ^ v_mixin[(i + 27) % 48];
            v_res[ 9] = v_mixup[ 9] ^ (v_mixup[28] & ~v_mixup[30]) ^ v_mixup[24] ^ v_mixup[31] ^ v_mixin[(i + 17) % 48];
            v_res[10] = v_mixup[10] ^ (v_mixup[29] & ~v_mixup[31]) ^ v_mixup[25] ^ v_mixup[32] ^ v_mixin[(i +  9) % 48];
            v_res[11] = v_mixup[11] ^ (v_mixup[30] & ~v_mixup[32]) ^ v_mixup[26] ^ v_mixup[33] ^ v_mixin[(i + 39) % 48];
            v_res[12] = v_mixup[12] ^ (v_mixup[31] & ~v_mixup[33]) ^ v_mixup[27] ^ v_mixup[34] ^ v_mixin[(i + 42) % 48];
            v_res[13] = v_mixup[13] ^ (v_mixup[32] & ~v_mixup[34]) ^ v_mixup[28] ^ v_mixup[35] ^ v_mixin[(i + 19) % 48];
            v_res[14] = v_mixup[14] ^ (v_mixup[33] & ~v_mixup[35]) ^ v_mixup[29] ^ v_mixup[36] ^ v_mixin[(i + 28) % 48];
            v_res[15] = v_mixup[15] ^ (v_mixup[34] & ~v_mixup[36]) ^ v_mixup[30] ^ v_mixup[37] ^ v_mixin[(i + 45) % 48];
            v_res[16] = v_mixup[16] ^ (v_mixup[35] & ~v_mixup[37]) ^ v_mixup[31] ^ v_mixup[38] ^ v_mixin[(i +  1) % 48];
            v_res[17] = v_mixup[17] ^ (v_mixup[36] & ~v_mixup[38]) ^ v_mixup[32] ^ v_mixup[39] ^ v_mixin[(i +  0) % 48];
            v_res[18] = v_mixup[18] ^ (v_mixup[37] & ~v_mixup[39]) ^ v_mixup[33] ^ v_mixup[40] ^ v_mixin[(i + 41) % 48];
            v_res[19] = v_mixup[19] ^ (v_mixup[38] & ~v_mixup[40]) ^ v_mixup[34] ^ v_mixup[41] ^ v_mixin[(i + 30) % 48];
            v_res[20] = v_mixup[20] ^ (v_mixup[39] & ~v_mixup[41]) ^ v_mixup[35] ^ v_mixup[42] ^ v_mixin[(i +  3) % 48];
            v_res[21] = v_mixup[21] ^ (v_mixup[40] & ~v_mixup[42]) ^ v_mixup[36] ^ v_mixup[43] ^ v_mixin[(i + 38) % 48];
            v_res[22] = v_mixup[22] ^ (v_mixup[41] & ~v_mixup[43]) ^ v_mixup[37] ^ v_mixup[44] ^ v_mixin[(i + 25) % 48];
            v_res[23] = v_mixup[23] ^ (v_mixup[42] & ~v_mixup[44]) ^ v_mixup[38] ^ v_mixup[45] ^ v_mixin[(i + 29) % 48];
            v_state_y1[48 * i +: 48] = {v_res, r_state_y[48 * i + 24 +: 24]};
        end
        
        for (i = 0; i < streams; i = i + 1) begin
            v_mixin = r_state_x ^ salts[48 * i +: 48];
            v_mixup = v_state_y1[48 * ((i + 1) % streams) +: 48];
            v_res[ 0] = v_mixup[ 0] ^ (v_mixup[19] & ~v_mixup[21]) ^ v_mixup[15] ^ v_mixup[22] ^ v_mixin[(i + 24) % 48];
            v_res[ 1] = v_mixup[ 1] ^ (v_mixup[20] & ~v_mixup[22]) ^ v_mixup[16] ^ v_mixup[23] ^ v_mixin[(i +  5) % 48];
            v_res[ 2] = v_mixup[ 2] ^ (v_mixup[21] & ~v_mixup[23]) ^ v_mixup[17] ^ v_mixup[24] ^ v_mixin[(i + 32) % 48];
            v_res[ 3] = v_mixup[ 3] ^ (v_mixup[22] & ~v_mixup[24]) ^ v_mixup[18] ^ v_mixup[25] ^ v_mixin[(i + 44) % 48];
            v_res[ 4] = v_mixup[ 4] ^ (v_mixup[23] & ~v_mixup[25]) ^ v_mixup[19] ^ v_mixup[26] ^ v_mixin[(i + 26) % 48];
            v_res[ 5] = v_mixup[ 5] ^ (v_mixup[24] & ~v_mixup[26]) ^ v_mixup[20] ^ v_mixup[27] ^ v_mixin[(i + 21) % 48];
            v_res[ 6] = v_mixup[ 6] ^ (v_mixup[25] & ~v_mixup[27]) ^ v_mixup[21] ^ v_mixup[28] ^ v_mixin[(i + 37) % 48];
            v_res[ 7] = v_mixup[ 7] ^ (v_mixup[26] & ~v_mixup[28]) ^ v_mixup[22] ^ v_mixup[29] ^ v_mixin[(i + 34) % 48];
            v_res[ 8] = v_mixup[ 8] ^ (v_mixup[27] & ~v_mixup[29]) ^ v_mixup[23] ^ v_mixup[30] ^ v_mixin[(i + 13) % 48];
            v_res[ 9] = v_mixup[ 9] ^ (v_mixup[28] & ~v_mixup[30]) ^ v_mixup[24] ^ v_mixup[31] ^ v_mixin[(i + 18) % 48];
            v_res[10] = v_mixup[10] ^ (v_mixup[29] & ~v_mixup[31]) ^ v_mixup[25] ^ v_mixup[32] ^ v_mixin[(i + 35) % 48];
            v_res[11] = v_mixup[11] ^ (v_mixup[30] & ~v_mixup[32]) ^ v_mixup[26] ^ v_mixup[33] ^ v_mixin[(i +  6) % 48];
            v_res[12] = v_mixup[12] ^ (v_mixup[31] & ~v_mixup[33]) ^ v_mixup[27] ^ v_mixup[34] ^ v_mixin[(i + 11) % 48];
            v_res[13] = v_mixup[13] ^ (v_mixup[32] & ~v_mixup[34]) ^ v_mixup[28] ^ v_mixup[35] ^ v_mixin[(i + 36) % 48];
            v_res[14] = v_mixup[14] ^ (v_mixup[33] & ~v_mixup[35]) ^ v_mixup[29] ^ v_mixup[36] ^ v_mixin[(i + 43) % 48];
            v_res[15] = v_mixup[15] ^ (v_mixup[34] & ~v_mixup[36]) ^ v_mixup[30] ^ v_mixup[37] ^ v_mixin[(i +  7) % 48];
            v_res[16] = v_mixup[16] ^ (v_mixup[35] & ~v_mixup[37]) ^ v_mixup[31] ^ v_mixup[38] ^ v_mixin[(i + 40) % 48];
            v_res[17] = v_mixup[17] ^ (v_mixup[36] & ~v_mixup[38]) ^ v_mixup[32] ^ v_mixup[39] ^ v_mixin[(i + 33) % 48];
            v_res[18] = v_mixup[18] ^ (v_mixup[37] & ~v_mixup[39]) ^ v_mixup[33] ^ v_mixup[40] ^ v_mixin[(i + 20) % 48];
            v_res[19] = v_mixup[19] ^ (v_mixup[38] & ~v_mixup[40]) ^ v_mixup[34] ^ v_mixup[41] ^ v_mixin[(i + 10) % 48];
            v_res[20] = v_mixup[20] ^ (v_mixup[39] & ~v_mixup[41]) ^ v_mixup[35] ^ v_mixup[42] ^ v_mixin[(i + 47) % 48];
            v_res[21] = v_mixup[21] ^ (v_mixup[40] & ~v_mixup[42]) ^ v_mixup[36] ^ v_mixup[43] ^ v_mixin[(i +  4) % 48];
            v_res[22] = v_mixup[22] ^ (v_mixup[41] & ~v_mixup[43]) ^ v_mixup[37] ^ v_mixup[44] ^ v_mixin[(i + 14) % 48];
            v_res[23] = v_mixup[23] ^ (v_mixup[42] & ~v_mixup[44]) ^ v_mixup[38] ^ v_mixup[45] ^ v_mixin[(i + 16) % 48];
            v_state_y2[48 * i +: 48] = {v_res, v_state_y1[48 * i + 24 +: 24]};
        end
        
    end
    
    always @(posedge clk) begin
        if (rst == 1'b1) begin
            
            r_state_x <= seed_x;
            r_state_y <= seed_y;
            
        end else if (enable == 1'b1) begin
            
            r_state_x[ 0] <= r_state_x[39] ^ r_state_x[20] ^ r_state_x[21] ^ r_state_x[31] ^ r_state_x[46];
            r_state_x[ 1] <= r_state_x[19] ^ r_state_x[29] ^ r_state_x[21] ^ r_state_x[ 5] ^ r_state_x[13] ^ r_state_x[ 0];
            r_state_x[ 2] <= r_state_x[ 6] ^ r_state_x[38] ^ r_state_x[20] ^ r_state_x[11] ^ r_state_x[ 7];
            r_state_x[ 3] <= r_state_x[10] ^ r_state_x[42] ^ r_state_x[18] ^ r_state_x[25] ^ r_state_x[26] ^ r_state_x[39];
            r_state_x[ 4] <= r_state_x[17] ^ r_state_x[38] ^ r_state_x[45] ^ r_state_x[11] ^ r_state_x[14];
            r_state_x[ 5] <= r_state_x[ 0] ^ r_state_x[ 1] ^ r_state_x[ 5] ^ r_state_x[28] ^ r_state_x[ 6] ^ r_state_x[39];
            r_state_x[ 6] <= r_state_x[32] ^ r_state_x[ 4] ^ r_state_x[26] ^ r_state_x[35] ^ r_state_x[ 5];
            r_state_x[ 7] <= r_state_x[21] ^ r_state_x[27] ^ r_state_x[10] ^ r_state_x[ 3] ^ r_state_x[22] ^ r_state_x[40];
            r_state_x[ 8] <= r_state_x[ 9] ^ r_state_x[31] ^ r_state_x[42] ^ r_state_x[33] ^ r_state_x[12];
            r_state_x[ 9] <= r_state_x[43] ^ r_state_x[ 6] ^ r_state_x[26] ^ r_state_x[47] ^ r_state_x[25] ^ r_state_x[27];
            r_state_x[10] <= r_state_x[ 1] ^ r_state_x[12] ^ r_state_x[41] ^ r_state_x[33] ^ r_state_x[29];
            r_state_x[11] <= r_state_x[30] ^ r_state_x[ 1] ^ r_state_x[10] ^ r_state_x[27] ^ r_state_x[24] ^ r_state_x[ 3];
            r_state_x[12] <= r_state_x[17] ^ r_state_x[ 9] ^ r_state_x[12] ^ r_state_x[43] ^ r_state_x[37];
            r_state_x[13] <= r_state_x[ 9] ^ r_state_x[11] ^ r_state_x[22] ^ r_state_x[21] ^ r_state_x[ 3] ^ r_state_x[28];
            r_state_x[14] <= r_state_x[18] ^ r_state_x[33] ^ r_state_x[13] ^ r_state_x[ 3] ^ r_state_x[ 2];
            r_state_x[15] <= r_state_x[42] ^ r_state_x[45] ^ r_state_x[36] ^ r_state_x[19] ^ r_state_x[34] ^ r_state_x[13];
            r_state_x[16] <= r_state_x[25] ^ r_state_x[22] ^ r_state_x[13] ^ r_state_x[28] ^ r_state_x[12];
            r_state_x[17] <= r_state_x[ 5] ^ r_state_x[40] ^ r_state_x[24] ^ r_state_x[12] ^ r_state_x[45] ^ r_state_x[14];
            r_state_x[18] <= r_state_x[ 2] ^ r_state_x[43] ^ r_state_x[ 7] ^ r_state_x[17] ^ r_state_x[ 4];
            r_state_x[19] <= r_state_x[ 5] ^ r_state_x[34] ^ r_state_x[32] ^ r_state_x[40] ^ r_state_x[28] ^ r_state_x[ 2];
            r_state_x[20] <= r_state_x[41] ^ r_state_x[44] ^ r_state_x[20] ^ r_state_x[ 1] ^ r_state_x[16];
            r_state_x[21] <= r_state_x[32] ^ r_state_x[12] ^ r_state_x[17] ^ r_state_x[44] ^ r_state_x[45] ^ r_state_x[23];
            r_state_x[22] <= r_state_x[30] ^ r_state_x[ 8] ^ r_state_x[24] ^ r_state_x[47] ^ r_state_x[18];
            r_state_x[23] <= r_state_x[14] ^ r_state_x[29] ^ r_state_x[ 0] ^ r_state_x[36] ^ r_state_x[18] ^ r_state_x[ 8];
            r_state_x[24] <= r_state_x[14] ^ r_state_x[33] ^ r_state_x[18] ^ r_state_x[34] ^ r_state_x[38];
            r_state_x[25] <= r_state_x[10] ^ r_state_x[32] ^ r_state_x[25] ^ r_state_x[ 2] ^ r_state_x[ 8] ^ r_state_x[38];
            r_state_x[26] <= r_state_x[47] ^ r_state_x[ 6] ^ r_state_x[36] ^ r_state_x[46] ^ r_state_x[34];
            r_state_x[27] <= r_state_x[ 7] ^ r_state_x[19] ^ r_state_x[23] ^ r_state_x[35] ^ r_state_x[26] ^ r_state_x[ 6];
            r_state_x[28] <= r_state_x[30] ^ r_state_x[32] ^ r_state_x[37] ^ r_state_x[16] ^ r_state_x[ 0];
            r_state_x[29] <= r_state_x[13] ^ r_state_x[17] ^ r_state_x[35] ^ r_state_x[29] ^ r_state_x[24] ^ r_state_x[47];
            r_state_x[30] <= r_state_x[11] ^ r_state_x[15] ^ r_state_x[45] ^ r_state_x[27] ^ r_state_x[ 8];
            r_state_x[31] <= r_state_x[46] ^ r_state_x[37] ^ r_state_x[21] ^ r_state_x[22] ^ r_state_x[24] ^ r_state_x[31];
            r_state_x[32] <= r_state_x[36] ^ r_state_x[26] ^ r_state_x[ 9] ^ r_state_x[27] ^ r_state_x[16];
            r_state_x[33] <= r_state_x[ 8] ^ r_state_x[ 4] ^ r_state_x[31] ^ r_state_x[22] ^ r_state_x[11] ^ r_state_x[23];
            r_state_x[34] <= r_state_x[ 1] ^ r_state_x[34] ^ r_state_x[19] ^ r_state_x[23] ^ r_state_x[47];
            r_state_x[35] <= r_state_x[30] ^ r_state_x[34] ^ r_state_x[40] ^ r_state_x[35] ^ r_state_x[32] ^ r_state_x[29];
            r_state_x[36] <= r_state_x[28] ^ r_state_x[ 4] ^ r_state_x[21] ^ r_state_x[44] ^ r_state_x[35];
            r_state_x[37] <= r_state_x[29] ^ r_state_x[39] ^ r_state_x[28] ^ r_state_x[36] ^ r_state_x[44] ^ r_state_x[ 7];
            r_state_x[38] <= r_state_x[42] ^ r_state_x[33] ^ r_state_x[ 6] ^ r_state_x[44] ^ r_state_x[16];
            r_state_x[39] <= r_state_x[ 8] ^ r_state_x[25] ^ r_state_x[36] ^ r_state_x[ 2] ^ r_state_x[19] ^ r_state_x[ 4];
            r_state_x[40] <= r_state_x[ 9] ^ r_state_x[25] ^ r_state_x[41] ^ r_state_x[31] ^ r_state_x[26];
            r_state_x[41] <= r_state_x[42] ^ r_state_x[35] ^ r_state_x[46] ^ r_state_x[15] ^ r_state_x[44] ^ r_state_x[33];
            r_state_x[42] <= r_state_x[35] ^ r_state_x[11] ^ r_state_x[ 9] ^ r_state_x[10] ^ r_state_x[23];
            r_state_x[43] <= r_state_x[46] ^ r_state_x[30] ^ r_state_x[26] ^ r_state_x[ 0] ^ r_state_x[ 7] ^ r_state_x[43];
            r_state_x[44] <= r_state_x[ 0] ^ r_state_x[39] ^ r_state_x[37] ^ r_state_x[40] ^ r_state_x[10];
            r_state_x[45] <= r_state_x[41] ^ r_state_x[15] ^ r_state_x[38] ^ r_state_x[20] ^ r_state_x[16] ^ r_state_x[12];
            r_state_x[46] <= r_state_x[15] ^ r_state_x[ 2] ^ r_state_x[17] ^ r_state_x[20] ^ r_state_x[42];
            r_state_x[47] <= r_state_x[ 2] ^ r_state_x[16] ^ r_state_x[17] ^ r_state_x[30] ^ r_state_x[22] ^ r_state_x[14];
            
            r_state_y <= v_state_y2;
            
        end
    end
    
endmodule

