// Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
// Available under the MIT License - see LICENSE.txt for details.

// This file was generated by `generate_verilog.py`.

module xormix128
    #(
        parameter streams = 1
    )
    (
        
        // clock and synchronous reset
        input wire clk,
        input wire rst,
        
        // configuration
        input wire [127 : 0] seed_x,
        input wire [128 * streams - 1 : 0] seed_y,
        
        // random number generator
        input wire enable,
        output wire [128 * streams - 1 : 0] result
        
    );
    
    localparam [128 * 128 - 1 : 0] salts = {
        128'h426d334d0210953d4fbc5eb23baa5b89, 128'hc660367182530702a8940562e769aa34, 128'h20afd57548c2a8194cae459746ef3ae2, 128'h6e6705040215fb0cc52b1723b77d8ca7,
        128'h96a7aabc97aeaf611bdb8ecfba049814, 128'h03c6b7bc51586c46c24dabc28e5104c1, 128'h2c009fa5c7f106bbb3c1825b2df6a2f6, 128'h8264b4091f7515269929e1ae0304ba9e,
        128'hea225519f1f55c7c16e4e2042546cf60, 128'h7a6982ded6aa1dfa91281fd5ec28196d, 128'h2136944a515be3f2c586e97599de219a, 128'h46d6eb2ac8cf719a2f12eb3b24e43b6b,
        128'hd6fe5e4c9f390bb6a5523bdaa7d672ce, 128'h9b99ae3537b38828c33f629c27654c29, 128'hbabeb4db43e98bfa20a036758e06ead4, 128'h6fe1bd7b2bd57f1d247318da9d130d0a,
        128'hb333a13878ed6467afc644cc4a7fba8a, 128'h0deea11cc253bddcc56da2d3f7a67ebc, 128'h11b01d55dd67c0c6e42ebea0b91fe54f, 128'h957b133698028d825c50a7eddc43a709,
        128'h7aa46106c2c9f687828e598d46c3b205, 128'h026439f83ae85ad94a127c8b01990c54, 128'hd5ae4ce8a7ce08fcffafc51ae8a5fb93, 128'hfdf7d79bc286586dc82f31311f9e6fca,
        128'hb334f15329dccb8cd1fd224b16e58d79, 128'h2863d4577783878fd8a58035655c3deb, 128'hda03176c01e50cdfe333b2d35fa015b6, 128'hf7ad24f6275633672634c1d79f45892d,
        128'h77b676851c7abda850afc4b495085f2c, 128'h3a6f475c1ecb7c13d996cd4441425a97, 128'h5ded207cd2e59c3da8fab36f9a21157f, 128'haa5cd73b8a0940b4fc5b3ac93926cd6a,
        128'ha355f9fd7fbf38fbcc8af45404fcc6be, 128'h397e57c92f9861547b24ca77b1cea27c, 128'h43cb709d85da0e5015a892a614986841, 128'h16e10d8df52cc48442a5d5256969aa9a,
        128'hbcbfbb13f986a39653cfbf7152d255d2, 128'h8aed916e4d36e7d3441a670f9380f30d, 128'hdbeaae962a0a698f5088ffd970256144, 128'h47128844e1e9270bf8df480e46fb4bc6,
        128'h65a35232d8d0dbe4790a2a7edd383fe0, 128'hdf182f5cab14cd39cf622a6d3bff6107, 128'h304931f308d9a27c11fb3a34ebedbe58, 128'h6950dd6b52bccfa99b73077b4199b59c,
        128'h65bc59d13c9f1c020606c022e177884c, 128'h857e76882355a43174069f24aaef94f3, 128'h20c9d2c922f18772e15b109bc8816f21, 128'he996c824b1a3b36d7bf40c8bf34821d5,
        128'hc8282c0619a4ab4ab3bb0c8667adf5ec, 128'h3696ca65addca66ffe04506afccfd23f, 128'hf3c2b154f0073720e761fae8b3d9d4cd, 128'h57960c3e5964c51b258678211c569f01,
        128'hc3c09bd89e26a8d21639de509e92ea9e, 128'hecd0cfe2ef3a2b6297a49e801f6214fe, 128'hc8d9279162d7730eca5dde8c906754f6, 128'h2a58c173ee11d4cafbc52f5cd9fc10bb,
        128'h923c62e69bde4f75b7b11297d6d46d4e, 128'hbfd591a612ab72bf2e682e54723518c7, 128'h17542b21cbec8d1495d843f20f9358b1, 128'haee9cf0e3d634e786dbe13197f40cc43,
        128'hb1af2c9c8c29a4e474d2338b5bad0afb, 128'ha0e7875e6c8cad2ef005cbf2adbb271c, 128'h730e3687735b1889b88a8e07cf291032, 128'hc5fbf5c3a47655d67e027925e7675b94,
        128'he20c664651c3d42328707a583af04239, 128'h0db87bc5c1e6728379b2d3a9b29b5521, 128'h97d615c53cd4923c614d38a4b90171b2, 128'hafd9af4b5cf7191f1ea35cb9fd2e62f9,
        128'h5e684ded016cb40d387f22aea9be95c6, 128'hb50a5ea77901f55f0434eb9ae66b5b33, 128'h6c65832f23f43eae6ef671a872141a82, 128'h80d258457c5bc95074c8d42a5a86f753,
        128'hae5910192d2aa1f4812c455df6cf92d0, 128'hc7feacc68d29d6fac50981d3c4088e92, 128'he3264b5d279d0575b9ec55cb7c363c39, 128'h02b67174dc3c1d518733c6cd6eb481e5,
        128'h7e1e701939f16165359190cf59a54f04, 128'he0bd8f5a2afeb40288b78f95c2b1984f, 128'h9a69338b783383a3f77adc87e60bcd0f, 128'h51981d2ac6601c9d7618b748f434fe31,
        128'hd9bf1cdf18b5d798beff10e60b0f9ac6, 128'h5933613e9f3214ebd8f5cd3857a43a64, 128'hd1d1ea95a0e8c0bf3d5e8a1f3bdac15b, 128'hf37135381111fd49faa63ff210faa19e,
        128'h85c76e9db31ad05530bb301a56b5218e, 128'h4c09a5bcf925c18d83718e4b5e59cb10, 128'h22b34c2e328f75bdc413ba90f1784dec, 128'hb7ab9b30669a5a6070e8ebe1e1b3a93e,
        128'h5e6024e9ee3f909d7ea8be62f7d37e6f, 128'h360f32162410c113d593ba723fc7d8c6, 128'hc8e4c9c9ff5231667370d2ffaaf50692, 128'hbf53a13583b45c0c767602e169da1734,
        128'h89d5524900fe6b6701072fd7e66b3aa3, 128'h301d9ba87df8d36c59a70c4f5c903b9d, 128'h658f170a3d5eb1382859bd534c03eddc, 128'hb499352d4c2c6d328f36503aa9322a10,
        128'h0e0a135ebd4ade22fa6502f6572ce3b5, 128'hf4ca5329109c00d36cefa419fabae38e, 128'hf5474098a6f8e72c88a90385e1bb7ec4, 128'h992ecb2546eba50e3c3a38d31856c3be,
        128'h20a9e692001abc41d2675a5ef558c9ca, 128'h3129867e0d1cae8743365f3838f1a6f2, 128'h14e1dbdb706146c87ccd29aa9617940c, 128'h7331f65d083f981679bdb371e10deab6,
        128'he0cda84666200d77794f864e524e3d05, 128'h0c2437807aaa24ff76d338b2696cbd46, 128'he8ebde2abd705c86d8f9fd86993a5e7b, 128'h0e751da1db416c312ebdc43faa118a3d,
        128'hb87010456ab8d88b8dd4c95dc5d17fc8, 128'ha30c5a4fca8b3b774f1f20a17431ea84, 128'h0102213a944f7a3b11412a294eaec4e3, 128'h5401edc6eacf9376c9b1740ae1682c7c,
        128'h51690ae0ba825d13e93a50422bf7c93e, 128'h131b25f5290a2d7c300c62a1f3f988a7, 128'h8333c010a7a2c1de068d13b2573889f5, 128'he84ed06e8ef90d826a4794d71bfde238,
        128'h0bfadd9ea78537202f0dc6387e490584, 128'h44c0eaa7acea07dc067157b612a796d0, 128'h58c7d8956ee996cb3201f2fcb2913077, 128'hd4d69acbbb4ef412be6edd8b7b1da9c4,
        128'hbb051ea62ebdb876a498e6edd1a7fff8, 128'hf91ab0c9d06a6fab8f59b935b3e19ad0, 128'hb310cd417e865701852c0f137baa77c1, 128'h9575b7768be3b6f63b37be5e9323f719,
        128'h103dca29fc314d3f05e11fe401cf6fbb, 128'h381bbba7d431439e3a7e57b7273176a3, 128'h7ff3ef25ad7380b8adf9a9bdbff1223e, 128'h13262f1ed94d35de5037b5ab9dbc3488
    };
    
    reg [127 : 0] r_state_x;
    reg [128 * streams - 1 : 0] r_state_y;
    
    reg [128 * streams - 1 : 0] v_state_y1;
    reg [128 * streams - 1 : 0] v_state_y2;
    
    reg [127 : 0] v_mixin;
    reg [127 : 0] v_mixup;
    reg [127 : 0] v_res;
    
    integer i;
    
    assign result = r_state_y;
    
    always @(*) begin
        
        for (i = 0; i < streams; i = i + 1) begin
            v_mixin = r_state_x ^ salts[128 * i +: 128];
            v_mixup = r_state_y[128 * ((i + 1) % streams) +: 128];
            v_res[  0] = v_mixup[  0] ^ (v_mixup[ 47] & ~v_mixup[ 61]) ^ v_mixup[ 56] ^ v_mixup[ 62] ^ v_mixin[(i +  68) % 128];
            v_res[  1] = v_mixup[  1] ^ (v_mixup[ 48] & ~v_mixup[ 62]) ^ v_mixup[ 57] ^ v_mixup[ 63] ^ v_mixin[(i +  77) % 128];
            v_res[  2] = v_mixup[  2] ^ (v_mixup[ 49] & ~v_mixup[ 63]) ^ v_mixup[ 58] ^ v_mixup[ 64] ^ v_mixin[(i +  52) % 128];
            v_res[  3] = v_mixup[  3] ^ (v_mixup[ 50] & ~v_mixup[ 64]) ^ v_mixup[ 59] ^ v_mixup[ 65] ^ v_mixin[(i + 101) % 128];
            v_res[  4] = v_mixup[  4] ^ (v_mixup[ 51] & ~v_mixup[ 65]) ^ v_mixup[ 60] ^ v_mixup[ 66] ^ v_mixin[(i + 107) % 128];
            v_res[  5] = v_mixup[  5] ^ (v_mixup[ 52] & ~v_mixup[ 66]) ^ v_mixup[ 61] ^ v_mixup[ 67] ^ v_mixin[(i + 124) % 128];
            v_res[  6] = v_mixup[  6] ^ (v_mixup[ 53] & ~v_mixup[ 67]) ^ v_mixup[ 62] ^ v_mixup[ 68] ^ v_mixin[(i + 117) % 128];
            v_res[  7] = v_mixup[  7] ^ (v_mixup[ 54] & ~v_mixup[ 68]) ^ v_mixup[ 63] ^ v_mixup[ 69] ^ v_mixin[(i + 113) % 128];
            v_res[  8] = v_mixup[  8] ^ (v_mixup[ 55] & ~v_mixup[ 69]) ^ v_mixup[ 64] ^ v_mixup[ 70] ^ v_mixin[(i +  96) % 128];
            v_res[  9] = v_mixup[  9] ^ (v_mixup[ 56] & ~v_mixup[ 70]) ^ v_mixup[ 65] ^ v_mixup[ 71] ^ v_mixin[(i +  92) % 128];
            v_res[ 10] = v_mixup[ 10] ^ (v_mixup[ 57] & ~v_mixup[ 71]) ^ v_mixup[ 66] ^ v_mixup[ 72] ^ v_mixin[(i +   7) % 128];
            v_res[ 11] = v_mixup[ 11] ^ (v_mixup[ 58] & ~v_mixup[ 72]) ^ v_mixup[ 67] ^ v_mixup[ 73] ^ v_mixin[(i +  25) % 128];
            v_res[ 12] = v_mixup[ 12] ^ (v_mixup[ 59] & ~v_mixup[ 73]) ^ v_mixup[ 68] ^ v_mixup[ 74] ^ v_mixin[(i +  21) % 128];
            v_res[ 13] = v_mixup[ 13] ^ (v_mixup[ 60] & ~v_mixup[ 74]) ^ v_mixup[ 69] ^ v_mixup[ 75] ^ v_mixin[(i +  28) % 128];
            v_res[ 14] = v_mixup[ 14] ^ (v_mixup[ 61] & ~v_mixup[ 75]) ^ v_mixup[ 70] ^ v_mixup[ 76] ^ v_mixin[(i +  60) % 128];
            v_res[ 15] = v_mixup[ 15] ^ (v_mixup[ 62] & ~v_mixup[ 76]) ^ v_mixup[ 71] ^ v_mixup[ 77] ^ v_mixin[(i +   1) % 128];
            v_res[ 16] = v_mixup[ 16] ^ (v_mixup[ 63] & ~v_mixup[ 77]) ^ v_mixup[ 72] ^ v_mixup[ 78] ^ v_mixin[(i +  17) % 128];
            v_res[ 17] = v_mixup[ 17] ^ (v_mixup[ 64] & ~v_mixup[ 78]) ^ v_mixup[ 73] ^ v_mixup[ 79] ^ v_mixin[(i +  26) % 128];
            v_res[ 18] = v_mixup[ 18] ^ (v_mixup[ 65] & ~v_mixup[ 79]) ^ v_mixup[ 74] ^ v_mixup[ 80] ^ v_mixin[(i +  44) % 128];
            v_res[ 19] = v_mixup[ 19] ^ (v_mixup[ 66] & ~v_mixup[ 80]) ^ v_mixup[ 75] ^ v_mixup[ 81] ^ v_mixin[(i +  27) % 128];
            v_res[ 20] = v_mixup[ 20] ^ (v_mixup[ 67] & ~v_mixup[ 81]) ^ v_mixup[ 76] ^ v_mixup[ 82] ^ v_mixin[(i +  59) % 128];
            v_res[ 21] = v_mixup[ 21] ^ (v_mixup[ 68] & ~v_mixup[ 82]) ^ v_mixup[ 77] ^ v_mixup[ 83] ^ v_mixin[(i + 127) % 128];
            v_res[ 22] = v_mixup[ 22] ^ (v_mixup[ 69] & ~v_mixup[ 83]) ^ v_mixup[ 78] ^ v_mixup[ 84] ^ v_mixin[(i +  46) % 128];
            v_res[ 23] = v_mixup[ 23] ^ (v_mixup[ 70] & ~v_mixup[ 84]) ^ v_mixup[ 79] ^ v_mixup[ 85] ^ v_mixin[(i + 110) % 128];
            v_res[ 24] = v_mixup[ 24] ^ (v_mixup[ 71] & ~v_mixup[ 85]) ^ v_mixup[ 80] ^ v_mixup[ 86] ^ v_mixin[(i +  83) % 128];
            v_res[ 25] = v_mixup[ 25] ^ (v_mixup[ 72] & ~v_mixup[ 86]) ^ v_mixup[ 81] ^ v_mixup[ 87] ^ v_mixin[(i +  98) % 128];
            v_res[ 26] = v_mixup[ 26] ^ (v_mixup[ 73] & ~v_mixup[ 87]) ^ v_mixup[ 82] ^ v_mixup[ 88] ^ v_mixin[(i +  54) % 128];
            v_res[ 27] = v_mixup[ 27] ^ (v_mixup[ 74] & ~v_mixup[ 88]) ^ v_mixup[ 83] ^ v_mixup[ 89] ^ v_mixin[(i + 126) % 128];
            v_res[ 28] = v_mixup[ 28] ^ (v_mixup[ 75] & ~v_mixup[ 89]) ^ v_mixup[ 84] ^ v_mixup[ 90] ^ v_mixin[(i +  29) % 128];
            v_res[ 29] = v_mixup[ 29] ^ (v_mixup[ 76] & ~v_mixup[ 90]) ^ v_mixup[ 85] ^ v_mixup[ 91] ^ v_mixin[(i +  95) % 128];
            v_res[ 30] = v_mixup[ 30] ^ (v_mixup[ 77] & ~v_mixup[ 91]) ^ v_mixup[ 86] ^ v_mixup[ 92] ^ v_mixin[(i +   0) % 128];
            v_res[ 31] = v_mixup[ 31] ^ (v_mixup[ 78] & ~v_mixup[ 92]) ^ v_mixup[ 87] ^ v_mixup[ 93] ^ v_mixin[(i +  20) % 128];
            v_res[ 32] = v_mixup[ 32] ^ (v_mixup[ 79] & ~v_mixup[ 93]) ^ v_mixup[ 88] ^ v_mixup[ 94] ^ v_mixin[(i +  66) % 128];
            v_res[ 33] = v_mixup[ 33] ^ (v_mixup[ 80] & ~v_mixup[ 94]) ^ v_mixup[ 89] ^ v_mixup[ 95] ^ v_mixin[(i +  89) % 128];
            v_res[ 34] = v_mixup[ 34] ^ (v_mixup[ 81] & ~v_mixup[ 95]) ^ v_mixup[ 90] ^ v_mixup[ 96] ^ v_mixin[(i +   9) % 128];
            v_res[ 35] = v_mixup[ 35] ^ (v_mixup[ 82] & ~v_mixup[ 96]) ^ v_mixup[ 91] ^ v_mixup[ 97] ^ v_mixin[(i +  19) % 128];
            v_res[ 36] = v_mixup[ 36] ^ (v_mixup[ 83] & ~v_mixup[ 97]) ^ v_mixup[ 92] ^ v_mixup[ 98] ^ v_mixin[(i +  91) % 128];
            v_res[ 37] = v_mixup[ 37] ^ (v_mixup[ 84] & ~v_mixup[ 98]) ^ v_mixup[ 93] ^ v_mixup[ 99] ^ v_mixin[(i +  10) % 128];
            v_res[ 38] = v_mixup[ 38] ^ (v_mixup[ 85] & ~v_mixup[ 99]) ^ v_mixup[ 94] ^ v_mixup[100] ^ v_mixin[(i +  58) % 128];
            v_res[ 39] = v_mixup[ 39] ^ (v_mixup[ 86] & ~v_mixup[100]) ^ v_mixup[ 95] ^ v_mixup[101] ^ v_mixin[(i + 120) % 128];
            v_res[ 40] = v_mixup[ 40] ^ (v_mixup[ 87] & ~v_mixup[101]) ^ v_mixup[ 96] ^ v_mixup[102] ^ v_mixin[(i +  11) % 128];
            v_res[ 41] = v_mixup[ 41] ^ (v_mixup[ 88] & ~v_mixup[102]) ^ v_mixup[ 97] ^ v_mixup[103] ^ v_mixin[(i + 100) % 128];
            v_res[ 42] = v_mixup[ 42] ^ (v_mixup[ 89] & ~v_mixup[103]) ^ v_mixup[ 98] ^ v_mixup[104] ^ v_mixin[(i +  49) % 128];
            v_res[ 43] = v_mixup[ 43] ^ (v_mixup[ 90] & ~v_mixup[104]) ^ v_mixup[ 99] ^ v_mixup[105] ^ v_mixin[(i +  82) % 128];
            v_res[ 44] = v_mixup[ 44] ^ (v_mixup[ 91] & ~v_mixup[105]) ^ v_mixup[100] ^ v_mixup[106] ^ v_mixin[(i +  75) % 128];
            v_res[ 45] = v_mixup[ 45] ^ (v_mixup[ 92] & ~v_mixup[106]) ^ v_mixup[101] ^ v_mixup[107] ^ v_mixin[(i +  16) % 128];
            v_res[ 46] = v_mixup[ 46] ^ (v_mixup[ 93] & ~v_mixup[107]) ^ v_mixup[102] ^ v_mixup[108] ^ v_mixin[(i +  36) % 128];
            v_res[ 47] = v_mixup[ 47] ^ (v_mixup[ 94] & ~v_mixup[108]) ^ v_mixup[103] ^ v_mixup[109] ^ v_mixin[(i + 103) % 128];
            v_res[ 48] = v_mixup[ 48] ^ (v_mixup[ 95] & ~v_mixup[109]) ^ v_mixup[104] ^ v_mixup[110] ^ v_mixin[(i +  62) % 128];
            v_res[ 49] = v_mixup[ 49] ^ (v_mixup[ 96] & ~v_mixup[110]) ^ v_mixup[105] ^ v_mixup[111] ^ v_mixin[(i +  50) % 128];
            v_res[ 50] = v_mixup[ 50] ^ (v_mixup[ 97] & ~v_mixup[111]) ^ v_mixup[106] ^ v_mixup[112] ^ v_mixin[(i +  65) % 128];
            v_res[ 51] = v_mixup[ 51] ^ (v_mixup[ 98] & ~v_mixup[112]) ^ v_mixup[107] ^ v_mixup[113] ^ v_mixin[(i + 112) % 128];
            v_res[ 52] = v_mixup[ 52] ^ (v_mixup[ 99] & ~v_mixup[113]) ^ v_mixup[108] ^ v_mixup[114] ^ v_mixin[(i +  24) % 128];
            v_res[ 53] = v_mixup[ 53] ^ (v_mixup[100] & ~v_mixup[114]) ^ v_mixup[109] ^ v_mixup[115] ^ v_mixin[(i +  33) % 128];
            v_res[ 54] = v_mixup[ 54] ^ (v_mixup[101] & ~v_mixup[115]) ^ v_mixup[110] ^ v_mixup[116] ^ v_mixin[(i +  51) % 128];
            v_res[ 55] = v_mixup[ 55] ^ (v_mixup[102] & ~v_mixup[116]) ^ v_mixup[111] ^ v_mixup[117] ^ v_mixin[(i +  86) % 128];
            v_res[ 56] = v_mixup[ 56] ^ (v_mixup[103] & ~v_mixup[117]) ^ v_mixup[112] ^ v_mixup[118] ^ v_mixin[(i +  40) % 128];
            v_res[ 57] = v_mixup[ 57] ^ (v_mixup[104] & ~v_mixup[118]) ^ v_mixup[113] ^ v_mixup[119] ^ v_mixin[(i + 102) % 128];
            v_res[ 58] = v_mixup[ 58] ^ (v_mixup[105] & ~v_mixup[119]) ^ v_mixup[114] ^ v_mixup[120] ^ v_mixin[(i +  48) % 128];
            v_res[ 59] = v_mixup[ 59] ^ (v_mixup[106] & ~v_mixup[120]) ^ v_mixup[115] ^ v_mixup[121] ^ v_mixin[(i +  81) % 128];
            v_res[ 60] = v_mixup[ 60] ^ (v_mixup[107] & ~v_mixup[121]) ^ v_mixup[116] ^ v_mixup[122] ^ v_mixin[(i + 125) % 128];
            v_res[ 61] = v_mixup[ 61] ^ (v_mixup[108] & ~v_mixup[122]) ^ v_mixup[117] ^ v_mixup[123] ^ v_mixin[(i +  34) % 128];
            v_res[ 62] = v_mixup[ 62] ^ (v_mixup[109] & ~v_mixup[123]) ^ v_mixup[118] ^ v_mixup[124] ^ v_mixin[(i +  56) % 128];
            v_res[ 63] = v_mixup[ 63] ^ (v_mixup[110] & ~v_mixup[124]) ^ v_mixup[119] ^ v_mixup[125] ^ v_mixin[(i +  73) % 128];
            v_state_y1[128 * i +: 128] = {v_res, r_state_y[128 * i + 64 +: 64]};
        end
        
        for (i = 0; i < streams; i = i + 1) begin
            v_mixin = r_state_x ^ salts[128 * i +: 128];
            v_mixup = v_state_y1[128 * ((i + 1) % streams) +: 128];
            v_res[  0] = v_mixup[  0] ^ (v_mixup[ 47] & ~v_mixup[ 61]) ^ v_mixup[ 56] ^ v_mixup[ 62] ^ v_mixin[(i +  32) % 128];
            v_res[  1] = v_mixup[  1] ^ (v_mixup[ 48] & ~v_mixup[ 62]) ^ v_mixup[ 57] ^ v_mixup[ 63] ^ v_mixin[(i + 118) % 128];
            v_res[  2] = v_mixup[  2] ^ (v_mixup[ 49] & ~v_mixup[ 63]) ^ v_mixup[ 58] ^ v_mixup[ 64] ^ v_mixin[(i +  78) % 128];
            v_res[  3] = v_mixup[  3] ^ (v_mixup[ 50] & ~v_mixup[ 64]) ^ v_mixup[ 59] ^ v_mixup[ 65] ^ v_mixin[(i +  69) % 128];
            v_res[  4] = v_mixup[  4] ^ (v_mixup[ 51] & ~v_mixup[ 65]) ^ v_mixup[ 60] ^ v_mixup[ 66] ^ v_mixin[(i +  45) % 128];
            v_res[  5] = v_mixup[  5] ^ (v_mixup[ 52] & ~v_mixup[ 66]) ^ v_mixup[ 61] ^ v_mixup[ 67] ^ v_mixin[(i +   6) % 128];
            v_res[  6] = v_mixup[  6] ^ (v_mixup[ 53] & ~v_mixup[ 67]) ^ v_mixup[ 62] ^ v_mixup[ 68] ^ v_mixin[(i +  93) % 128];
            v_res[  7] = v_mixup[  7] ^ (v_mixup[ 54] & ~v_mixup[ 68]) ^ v_mixup[ 63] ^ v_mixup[ 69] ^ v_mixin[(i +  53) % 128];
            v_res[  8] = v_mixup[  8] ^ (v_mixup[ 55] & ~v_mixup[ 69]) ^ v_mixup[ 64] ^ v_mixup[ 70] ^ v_mixin[(i + 116) % 128];
            v_res[  9] = v_mixup[  9] ^ (v_mixup[ 56] & ~v_mixup[ 70]) ^ v_mixup[ 65] ^ v_mixup[ 71] ^ v_mixin[(i +  84) % 128];
            v_res[ 10] = v_mixup[ 10] ^ (v_mixup[ 57] & ~v_mixup[ 71]) ^ v_mixup[ 66] ^ v_mixup[ 72] ^ v_mixin[(i +   3) % 128];
            v_res[ 11] = v_mixup[ 11] ^ (v_mixup[ 58] & ~v_mixup[ 72]) ^ v_mixup[ 67] ^ v_mixup[ 73] ^ v_mixin[(i +  97) % 128];
            v_res[ 12] = v_mixup[ 12] ^ (v_mixup[ 59] & ~v_mixup[ 73]) ^ v_mixup[ 68] ^ v_mixup[ 74] ^ v_mixin[(i +  99) % 128];
            v_res[ 13] = v_mixup[ 13] ^ (v_mixup[ 60] & ~v_mixup[ 74]) ^ v_mixup[ 69] ^ v_mixup[ 75] ^ v_mixin[(i +  39) % 128];
            v_res[ 14] = v_mixup[ 14] ^ (v_mixup[ 61] & ~v_mixup[ 75]) ^ v_mixup[ 70] ^ v_mixup[ 76] ^ v_mixin[(i +  70) % 128];
            v_res[ 15] = v_mixup[ 15] ^ (v_mixup[ 62] & ~v_mixup[ 76]) ^ v_mixup[ 71] ^ v_mixup[ 77] ^ v_mixin[(i + 119) % 128];
            v_res[ 16] = v_mixup[ 16] ^ (v_mixup[ 63] & ~v_mixup[ 77]) ^ v_mixup[ 72] ^ v_mixup[ 78] ^ v_mixin[(i +  72) % 128];
            v_res[ 17] = v_mixup[ 17] ^ (v_mixup[ 64] & ~v_mixup[ 78]) ^ v_mixup[ 73] ^ v_mixup[ 79] ^ v_mixin[(i +  14) % 128];
            v_res[ 18] = v_mixup[ 18] ^ (v_mixup[ 65] & ~v_mixup[ 79]) ^ v_mixup[ 74] ^ v_mixup[ 80] ^ v_mixin[(i +  64) % 128];
            v_res[ 19] = v_mixup[ 19] ^ (v_mixup[ 66] & ~v_mixup[ 80]) ^ v_mixup[ 75] ^ v_mixup[ 81] ^ v_mixin[(i + 121) % 128];
            v_res[ 20] = v_mixup[ 20] ^ (v_mixup[ 67] & ~v_mixup[ 81]) ^ v_mixup[ 76] ^ v_mixup[ 82] ^ v_mixin[(i +  76) % 128];
            v_res[ 21] = v_mixup[ 21] ^ (v_mixup[ 68] & ~v_mixup[ 82]) ^ v_mixup[ 77] ^ v_mixup[ 83] ^ v_mixin[(i +  22) % 128];
            v_res[ 22] = v_mixup[ 22] ^ (v_mixup[ 69] & ~v_mixup[ 83]) ^ v_mixup[ 78] ^ v_mixup[ 84] ^ v_mixin[(i + 104) % 128];
            v_res[ 23] = v_mixup[ 23] ^ (v_mixup[ 70] & ~v_mixup[ 84]) ^ v_mixup[ 79] ^ v_mixup[ 85] ^ v_mixin[(i +  63) % 128];
            v_res[ 24] = v_mixup[ 24] ^ (v_mixup[ 71] & ~v_mixup[ 85]) ^ v_mixup[ 80] ^ v_mixup[ 86] ^ v_mixin[(i + 106) % 128];
            v_res[ 25] = v_mixup[ 25] ^ (v_mixup[ 72] & ~v_mixup[ 86]) ^ v_mixup[ 81] ^ v_mixup[ 87] ^ v_mixin[(i +  15) % 128];
            v_res[ 26] = v_mixup[ 26] ^ (v_mixup[ 73] & ~v_mixup[ 87]) ^ v_mixup[ 82] ^ v_mixup[ 88] ^ v_mixin[(i +   2) % 128];
            v_res[ 27] = v_mixup[ 27] ^ (v_mixup[ 74] & ~v_mixup[ 88]) ^ v_mixup[ 83] ^ v_mixup[ 89] ^ v_mixin[(i +  42) % 128];
            v_res[ 28] = v_mixup[ 28] ^ (v_mixup[ 75] & ~v_mixup[ 89]) ^ v_mixup[ 84] ^ v_mixup[ 90] ^ v_mixin[(i +  41) % 128];
            v_res[ 29] = v_mixup[ 29] ^ (v_mixup[ 76] & ~v_mixup[ 90]) ^ v_mixup[ 85] ^ v_mixup[ 91] ^ v_mixin[(i +  18) % 128];
            v_res[ 30] = v_mixup[ 30] ^ (v_mixup[ 77] & ~v_mixup[ 91]) ^ v_mixup[ 86] ^ v_mixup[ 92] ^ v_mixin[(i + 123) % 128];
            v_res[ 31] = v_mixup[ 31] ^ (v_mixup[ 78] & ~v_mixup[ 92]) ^ v_mixup[ 87] ^ v_mixup[ 93] ^ v_mixin[(i + 114) % 128];
            v_res[ 32] = v_mixup[ 32] ^ (v_mixup[ 79] & ~v_mixup[ 93]) ^ v_mixup[ 88] ^ v_mixup[ 94] ^ v_mixin[(i +   8) % 128];
            v_res[ 33] = v_mixup[ 33] ^ (v_mixup[ 80] & ~v_mixup[ 94]) ^ v_mixup[ 89] ^ v_mixup[ 95] ^ v_mixin[(i + 115) % 128];
            v_res[ 34] = v_mixup[ 34] ^ (v_mixup[ 81] & ~v_mixup[ 95]) ^ v_mixup[ 90] ^ v_mixup[ 96] ^ v_mixin[(i + 108) % 128];
            v_res[ 35] = v_mixup[ 35] ^ (v_mixup[ 82] & ~v_mixup[ 96]) ^ v_mixup[ 91] ^ v_mixup[ 97] ^ v_mixin[(i +  85) % 128];
            v_res[ 36] = v_mixup[ 36] ^ (v_mixup[ 83] & ~v_mixup[ 97]) ^ v_mixup[ 92] ^ v_mixup[ 98] ^ v_mixin[(i +  80) % 128];
            v_res[ 37] = v_mixup[ 37] ^ (v_mixup[ 84] & ~v_mixup[ 98]) ^ v_mixup[ 93] ^ v_mixup[ 99] ^ v_mixin[(i +  37) % 128];
            v_res[ 38] = v_mixup[ 38] ^ (v_mixup[ 85] & ~v_mixup[ 99]) ^ v_mixup[ 94] ^ v_mixup[100] ^ v_mixin[(i +  35) % 128];
            v_res[ 39] = v_mixup[ 39] ^ (v_mixup[ 86] & ~v_mixup[100]) ^ v_mixup[ 95] ^ v_mixup[101] ^ v_mixin[(i +  13) % 128];
            v_res[ 40] = v_mixup[ 40] ^ (v_mixup[ 87] & ~v_mixup[101]) ^ v_mixup[ 96] ^ v_mixup[102] ^ v_mixin[(i +  30) % 128];
            v_res[ 41] = v_mixup[ 41] ^ (v_mixup[ 88] & ~v_mixup[102]) ^ v_mixup[ 97] ^ v_mixup[103] ^ v_mixin[(i +  87) % 128];
            v_res[ 42] = v_mixup[ 42] ^ (v_mixup[ 89] & ~v_mixup[103]) ^ v_mixup[ 98] ^ v_mixup[104] ^ v_mixin[(i +  79) % 128];
            v_res[ 43] = v_mixup[ 43] ^ (v_mixup[ 90] & ~v_mixup[104]) ^ v_mixup[ 99] ^ v_mixup[105] ^ v_mixin[(i +  61) % 128];
            v_res[ 44] = v_mixup[ 44] ^ (v_mixup[ 91] & ~v_mixup[105]) ^ v_mixup[100] ^ v_mixup[106] ^ v_mixin[(i +   4) % 128];
            v_res[ 45] = v_mixup[ 45] ^ (v_mixup[ 92] & ~v_mixup[106]) ^ v_mixup[101] ^ v_mixup[107] ^ v_mixin[(i + 109) % 128];
            v_res[ 46] = v_mixup[ 46] ^ (v_mixup[ 93] & ~v_mixup[107]) ^ v_mixup[102] ^ v_mixup[108] ^ v_mixin[(i + 111) % 128];
            v_res[ 47] = v_mixup[ 47] ^ (v_mixup[ 94] & ~v_mixup[108]) ^ v_mixup[103] ^ v_mixup[109] ^ v_mixin[(i +  43) % 128];
            v_res[ 48] = v_mixup[ 48] ^ (v_mixup[ 95] & ~v_mixup[109]) ^ v_mixup[104] ^ v_mixup[110] ^ v_mixin[(i +  67) % 128];
            v_res[ 49] = v_mixup[ 49] ^ (v_mixup[ 96] & ~v_mixup[110]) ^ v_mixup[105] ^ v_mixup[111] ^ v_mixin[(i +  55) % 128];
            v_res[ 50] = v_mixup[ 50] ^ (v_mixup[ 97] & ~v_mixup[111]) ^ v_mixup[106] ^ v_mixup[112] ^ v_mixin[(i +  23) % 128];
            v_res[ 51] = v_mixup[ 51] ^ (v_mixup[ 98] & ~v_mixup[112]) ^ v_mixup[107] ^ v_mixup[113] ^ v_mixin[(i +  12) % 128];
            v_res[ 52] = v_mixup[ 52] ^ (v_mixup[ 99] & ~v_mixup[113]) ^ v_mixup[108] ^ v_mixup[114] ^ v_mixin[(i +  74) % 128];
            v_res[ 53] = v_mixup[ 53] ^ (v_mixup[100] & ~v_mixup[114]) ^ v_mixup[109] ^ v_mixup[115] ^ v_mixin[(i +  47) % 128];
            v_res[ 54] = v_mixup[ 54] ^ (v_mixup[101] & ~v_mixup[115]) ^ v_mixup[110] ^ v_mixup[116] ^ v_mixin[(i + 105) % 128];
            v_res[ 55] = v_mixup[ 55] ^ (v_mixup[102] & ~v_mixup[116]) ^ v_mixup[111] ^ v_mixup[117] ^ v_mixin[(i +  90) % 128];
            v_res[ 56] = v_mixup[ 56] ^ (v_mixup[103] & ~v_mixup[117]) ^ v_mixup[112] ^ v_mixup[118] ^ v_mixin[(i +  94) % 128];
            v_res[ 57] = v_mixup[ 57] ^ (v_mixup[104] & ~v_mixup[118]) ^ v_mixup[113] ^ v_mixup[119] ^ v_mixin[(i +  71) % 128];
            v_res[ 58] = v_mixup[ 58] ^ (v_mixup[105] & ~v_mixup[119]) ^ v_mixup[114] ^ v_mixup[120] ^ v_mixin[(i + 122) % 128];
            v_res[ 59] = v_mixup[ 59] ^ (v_mixup[106] & ~v_mixup[120]) ^ v_mixup[115] ^ v_mixup[121] ^ v_mixin[(i +  57) % 128];
            v_res[ 60] = v_mixup[ 60] ^ (v_mixup[107] & ~v_mixup[121]) ^ v_mixup[116] ^ v_mixup[122] ^ v_mixin[(i +  31) % 128];
            v_res[ 61] = v_mixup[ 61] ^ (v_mixup[108] & ~v_mixup[122]) ^ v_mixup[117] ^ v_mixup[123] ^ v_mixin[(i +  88) % 128];
            v_res[ 62] = v_mixup[ 62] ^ (v_mixup[109] & ~v_mixup[123]) ^ v_mixup[118] ^ v_mixup[124] ^ v_mixin[(i +   5) % 128];
            v_res[ 63] = v_mixup[ 63] ^ (v_mixup[110] & ~v_mixup[124]) ^ v_mixup[119] ^ v_mixup[125] ^ v_mixin[(i +  38) % 128];
            v_state_y2[128 * i +: 128] = {v_res, v_state_y1[128 * i + 64 +: 64]};
        end
        
    end
    
    always @(posedge clk) begin
        if (rst == 1'b1) begin
            
            r_state_x <= seed_x;
            r_state_y <= seed_y;
            
        end else if (enable == 1'b1) begin
            
            r_state_x[  0] <= r_state_x[ 93] ^ r_state_x[ 67] ^ r_state_x[ 22] ^ r_state_x[113] ^ r_state_x[ 35];
            r_state_x[  1] <= r_state_x[ 38] ^ r_state_x[ 84] ^ r_state_x[ 91] ^ r_state_x[ 47] ^ r_state_x[ 95] ^ r_state_x[124];
            r_state_x[  2] <= r_state_x[114] ^ r_state_x[ 68] ^ r_state_x[ 23] ^ r_state_x[  3] ^ r_state_x[ 17];
            r_state_x[  3] <= r_state_x[ 50] ^ r_state_x[ 29] ^ r_state_x[127] ^ r_state_x[ 54] ^ r_state_x[ 20] ^ r_state_x[ 39];
            r_state_x[  4] <= r_state_x[ 69] ^ r_state_x[ 19] ^ r_state_x[  1] ^ r_state_x[  7] ^ r_state_x[108];
            r_state_x[  5] <= r_state_x[ 77] ^ r_state_x[ 69] ^ r_state_x[ 43] ^ r_state_x[ 87] ^ r_state_x[ 28] ^ r_state_x[121];
            r_state_x[  6] <= r_state_x[103] ^ r_state_x[ 62] ^ r_state_x[ 50] ^ r_state_x[ 96] ^ r_state_x[118];
            r_state_x[  7] <= r_state_x[  6] ^ r_state_x[ 49] ^ r_state_x[125] ^ r_state_x[ 63] ^ r_state_x[ 46] ^ r_state_x[ 87];
            r_state_x[  8] <= r_state_x[ 92] ^ r_state_x[  5] ^ r_state_x[ 45] ^ r_state_x[  3] ^ r_state_x[ 95];
            r_state_x[  9] <= r_state_x[ 55] ^ r_state_x[ 37] ^ r_state_x[ 10] ^ r_state_x[101] ^ r_state_x[107] ^ r_state_x[ 84];
            r_state_x[ 10] <= r_state_x[ 21] ^ r_state_x[ 32] ^ r_state_x[ 46] ^ r_state_x[ 19] ^ r_state_x[113];
            r_state_x[ 11] <= r_state_x[116] ^ r_state_x[ 34] ^ r_state_x[  8] ^ r_state_x[ 41] ^ r_state_x[ 47] ^ r_state_x[ 93];
            r_state_x[ 12] <= r_state_x[ 37] ^ r_state_x[125] ^ r_state_x[ 38] ^ r_state_x[102] ^ r_state_x[ 40];
            r_state_x[ 13] <= r_state_x[ 72] ^ r_state_x[ 89] ^ r_state_x[127] ^ r_state_x[ 31] ^ r_state_x[113] ^ r_state_x[ 51];
            r_state_x[ 14] <= r_state_x[ 87] ^ r_state_x[  6] ^ r_state_x[ 59] ^ r_state_x[  3] ^ r_state_x[  9];
            r_state_x[ 15] <= r_state_x[ 66] ^ r_state_x[  5] ^ r_state_x[ 52] ^ r_state_x[ 18] ^ r_state_x[ 56] ^ r_state_x[ 75];
            r_state_x[ 16] <= r_state_x[ 28] ^ r_state_x[ 33] ^ r_state_x[ 14] ^ r_state_x[ 27] ^ r_state_x[ 98];
            r_state_x[ 17] <= r_state_x[  7] ^ r_state_x[ 72] ^ r_state_x[  9] ^ r_state_x[  2] ^ r_state_x[ 30] ^ r_state_x[ 29];
            r_state_x[ 18] <= r_state_x[106] ^ r_state_x[110] ^ r_state_x[ 40] ^ r_state_x[ 98] ^ r_state_x[ 42];
            r_state_x[ 19] <= r_state_x[100] ^ r_state_x[ 60] ^ r_state_x[ 30] ^ r_state_x[105] ^ r_state_x[ 28] ^ r_state_x[ 50];
            r_state_x[ 20] <= r_state_x[ 63] ^ r_state_x[  5] ^ r_state_x[ 51] ^ r_state_x[ 41] ^ r_state_x[ 57];
            r_state_x[ 21] <= r_state_x[108] ^ r_state_x[ 12] ^ r_state_x[ 14] ^ r_state_x[ 35] ^ r_state_x[ 36] ^ r_state_x[ 96];
            r_state_x[ 22] <= r_state_x[ 56] ^ r_state_x[ 73] ^ r_state_x[ 62] ^ r_state_x[ 86] ^ r_state_x[ 26];
            r_state_x[ 23] <= r_state_x[ 58] ^ r_state_x[ 91] ^ r_state_x[119] ^ r_state_x[ 44] ^ r_state_x[ 65] ^ r_state_x[ 89];
            r_state_x[ 24] <= r_state_x[ 34] ^ r_state_x[123] ^ r_state_x[100] ^ r_state_x[111] ^ r_state_x[ 59];
            r_state_x[ 25] <= r_state_x[124] ^ r_state_x[119] ^ r_state_x[ 72] ^ r_state_x[ 61] ^ r_state_x[ 19] ^ r_state_x[ 63];
            r_state_x[ 26] <= r_state_x[  5] ^ r_state_x[ 78] ^ r_state_x[114] ^ r_state_x[ 27] ^ r_state_x[ 55];
            r_state_x[ 27] <= r_state_x[ 41] ^ r_state_x[ 32] ^ r_state_x[ 54] ^ r_state_x[ 52] ^ r_state_x[ 67] ^ r_state_x[ 11];
            r_state_x[ 28] <= r_state_x[ 33] ^ r_state_x[ 89] ^ r_state_x[  7] ^ r_state_x[ 14] ^ r_state_x[ 71];
            r_state_x[ 29] <= r_state_x[109] ^ r_state_x[ 17] ^ r_state_x[ 80] ^ r_state_x[ 94] ^ r_state_x[ 54] ^ r_state_x[ 11];
            r_state_x[ 30] <= r_state_x[117] ^ r_state_x[ 29] ^ r_state_x[ 30] ^ r_state_x[ 33] ^ r_state_x[  0];
            r_state_x[ 31] <= r_state_x[ 31] ^ r_state_x[ 85] ^ r_state_x[127] ^ r_state_x[102] ^ r_state_x[ 96] ^ r_state_x[ 95];
            r_state_x[ 32] <= r_state_x[ 80] ^ r_state_x[ 42] ^ r_state_x[ 82] ^ r_state_x[101] ^ r_state_x[ 68];
            r_state_x[ 33] <= r_state_x[ 55] ^ r_state_x[ 85] ^ r_state_x[ 80] ^ r_state_x[ 95] ^ r_state_x[105] ^ r_state_x[ 70];
            r_state_x[ 34] <= r_state_x[122] ^ r_state_x[116] ^ r_state_x[ 88] ^ r_state_x[ 41] ^ r_state_x[ 22];
            r_state_x[ 35] <= r_state_x[ 97] ^ r_state_x[116] ^ r_state_x[ 36] ^ r_state_x[ 83] ^ r_state_x[ 82] ^ r_state_x[123];
            r_state_x[ 36] <= r_state_x[ 21] ^ r_state_x[ 82] ^ r_state_x[ 54] ^ r_state_x[111] ^ r_state_x[101];
            r_state_x[ 37] <= r_state_x[ 99] ^ r_state_x[ 76] ^ r_state_x[  8] ^ r_state_x[ 10] ^ r_state_x[ 48] ^ r_state_x[126];
            r_state_x[ 38] <= r_state_x[  8] ^ r_state_x[ 90] ^ r_state_x[ 48] ^ r_state_x[ 56] ^ r_state_x[117];
            r_state_x[ 39] <= r_state_x[111] ^ r_state_x[120] ^ r_state_x[ 77] ^ r_state_x[ 53] ^ r_state_x[123] ^ r_state_x[ 79];
            r_state_x[ 40] <= r_state_x[104] ^ r_state_x[ 38] ^ r_state_x[108] ^ r_state_x[106] ^ r_state_x[102];
            r_state_x[ 41] <= r_state_x[ 13] ^ r_state_x[ 26] ^ r_state_x[118] ^ r_state_x[120] ^ r_state_x[ 14] ^ r_state_x[ 73];
            r_state_x[ 42] <= r_state_x[ 24] ^ r_state_x[122] ^ r_state_x[ 12] ^ r_state_x[  1] ^ r_state_x[ 65];
            r_state_x[ 43] <= r_state_x[ 18] ^ r_state_x[ 33] ^ r_state_x[ 94] ^ r_state_x[ 76] ^ r_state_x[ 64] ^ r_state_x[  4];
            r_state_x[ 44] <= r_state_x[  9] ^ r_state_x[102] ^ r_state_x[ 31] ^ r_state_x[ 24] ^ r_state_x[ 86];
            r_state_x[ 45] <= r_state_x[ 16] ^ r_state_x[ 45] ^ r_state_x[ 39] ^ r_state_x[ 31] ^ r_state_x[ 67] ^ r_state_x[108];
            r_state_x[ 46] <= r_state_x[ 33] ^ r_state_x[ 58] ^ r_state_x[  0] ^ r_state_x[ 81] ^ r_state_x[ 93];
            r_state_x[ 47] <= r_state_x[ 63] ^ r_state_x[110] ^ r_state_x[ 74] ^ r_state_x[ 56] ^ r_state_x[ 47] ^ r_state_x[ 23];
            r_state_x[ 48] <= r_state_x[ 96] ^ r_state_x[ 37] ^ r_state_x[ 32] ^ r_state_x[ 56] ^ r_state_x[ 97];
            r_state_x[ 49] <= r_state_x[ 35] ^ r_state_x[ 18] ^ r_state_x[ 93] ^ r_state_x[ 12] ^ r_state_x[105] ^ r_state_x[121];
            r_state_x[ 50] <= r_state_x[  2] ^ r_state_x[112] ^ r_state_x[117] ^ r_state_x[ 76] ^ r_state_x[ 51];
            r_state_x[ 51] <= r_state_x[  6] ^ r_state_x[106] ^ r_state_x[110] ^ r_state_x[ 68] ^ r_state_x[ 13] ^ r_state_x[ 15];
            r_state_x[ 52] <= r_state_x[ 12] ^ r_state_x[ 76] ^ r_state_x[107] ^ r_state_x[ 16] ^ r_state_x[121];
            r_state_x[ 53] <= r_state_x[124] ^ r_state_x[ 95] ^ r_state_x[ 85] ^ r_state_x[ 28] ^ r_state_x[ 13] ^ r_state_x[  6];
            r_state_x[ 54] <= r_state_x[123] ^ r_state_x[ 28] ^ r_state_x[  5] ^ r_state_x[ 61] ^ r_state_x[ 59];
            r_state_x[ 55] <= r_state_x[ 26] ^ r_state_x[ 76] ^ r_state_x[ 30] ^ r_state_x[ 99] ^ r_state_x[ 25] ^ r_state_x[ 16];
            r_state_x[ 56] <= r_state_x[ 66] ^ r_state_x[ 89] ^ r_state_x[122] ^ r_state_x[ 79] ^ r_state_x[103];
            r_state_x[ 57] <= r_state_x[107] ^ r_state_x[ 15] ^ r_state_x[ 29] ^ r_state_x[ 34] ^ r_state_x[ 83] ^ r_state_x[116];
            r_state_x[ 58] <= r_state_x[ 16] ^ r_state_x[ 53] ^ r_state_x[107] ^ r_state_x[ 98] ^ r_state_x[ 37];
            r_state_x[ 59] <= r_state_x[ 49] ^ r_state_x[104] ^ r_state_x[ 94] ^ r_state_x[109] ^ r_state_x[112] ^ r_state_x[ 79];
            r_state_x[ 60] <= r_state_x[ 12] ^ r_state_x[ 57] ^ r_state_x[ 61] ^ r_state_x[ 70] ^ r_state_x[ 20];
            r_state_x[ 61] <= r_state_x[ 29] ^ r_state_x[ 97] ^ r_state_x[ 71] ^ r_state_x[ 78] ^ r_state_x[ 53] ^ r_state_x[ 74];
            r_state_x[ 62] <= r_state_x[ 16] ^ r_state_x[108] ^ r_state_x[111] ^ r_state_x[ 90] ^ r_state_x[  1];
            r_state_x[ 63] <= r_state_x[ 59] ^ r_state_x[ 91] ^ r_state_x[114] ^ r_state_x[122] ^ r_state_x[ 50] ^ r_state_x[ 99];
            r_state_x[ 64] <= r_state_x[113] ^ r_state_x[125] ^ r_state_x[ 26] ^ r_state_x[ 57] ^ r_state_x[ 51];
            r_state_x[ 65] <= r_state_x[100] ^ r_state_x[ 85] ^ r_state_x[114] ^ r_state_x[ 86] ^ r_state_x[106] ^ r_state_x[121];
            r_state_x[ 66] <= r_state_x[ 81] ^ r_state_x[ 21] ^ r_state_x[ 42] ^ r_state_x[  9] ^ r_state_x[ 15];
            r_state_x[ 67] <= r_state_x[ 63] ^ r_state_x[127] ^ r_state_x[ 45] ^ r_state_x[ 18] ^ r_state_x[ 13] ^ r_state_x[ 74];
            r_state_x[ 68] <= r_state_x[ 53] ^ r_state_x[ 55] ^ r_state_x[  2] ^ r_state_x[ 46] ^ r_state_x[ 84];
            r_state_x[ 69] <= r_state_x[ 29] ^ r_state_x[ 67] ^ r_state_x[ 62] ^ r_state_x[125] ^ r_state_x[127] ^ r_state_x[ 84];
            r_state_x[ 70] <= r_state_x[  8] ^ r_state_x[ 55] ^ r_state_x[ 78] ^ r_state_x[ 53] ^ r_state_x[ 41];
            r_state_x[ 71] <= r_state_x[ 11] ^ r_state_x[ 81] ^ r_state_x[ 37] ^ r_state_x[125] ^ r_state_x[ 32] ^ r_state_x[ 61];
            r_state_x[ 72] <= r_state_x[ 94] ^ r_state_x[ 82] ^ r_state_x[ 91] ^ r_state_x[ 58] ^ r_state_x[ 46];
            r_state_x[ 73] <= r_state_x[ 43] ^ r_state_x[ 15] ^ r_state_x[119] ^ r_state_x[ 47] ^ r_state_x[ 87] ^ r_state_x[ 62];
            r_state_x[ 74] <= r_state_x[126] ^ r_state_x[ 85] ^ r_state_x[ 82] ^ r_state_x[ 93] ^ r_state_x[ 90];
            r_state_x[ 75] <= r_state_x[ 15] ^ r_state_x[ 99] ^ r_state_x[ 59] ^ r_state_x[  4] ^ r_state_x[ 65] ^ r_state_x[  0];
            r_state_x[ 76] <= r_state_x[ 64] ^ r_state_x[ 17] ^ r_state_x[ 12] ^ r_state_x[ 10] ^ r_state_x[120];
            r_state_x[ 77] <= r_state_x[  1] ^ r_state_x[ 31] ^ r_state_x[115] ^ r_state_x[ 45] ^ r_state_x[ 43] ^ r_state_x[ 64];
            r_state_x[ 78] <= r_state_x[123] ^ r_state_x[ 24] ^ r_state_x[  7] ^ r_state_x[ 66] ^ r_state_x[ 73];
            r_state_x[ 79] <= r_state_x[103] ^ r_state_x[ 39] ^ r_state_x[ 54] ^ r_state_x[ 59] ^ r_state_x[ 74] ^ r_state_x[ 78];
            r_state_x[ 80] <= r_state_x[ 53] ^ r_state_x[ 12] ^ r_state_x[ 57] ^ r_state_x[100] ^ r_state_x[115];
            r_state_x[ 81] <= r_state_x[107] ^ r_state_x[ 39] ^ r_state_x[ 80] ^ r_state_x[ 75] ^ r_state_x[ 94] ^ r_state_x[ 49];
            r_state_x[ 82] <= r_state_x[ 25] ^ r_state_x[  1] ^ r_state_x[ 88] ^ r_state_x[124] ^ r_state_x[ 58];
            r_state_x[ 83] <= r_state_x[ 75] ^ r_state_x[103] ^ r_state_x[ 86] ^ r_state_x[ 79] ^ r_state_x[ 88] ^ r_state_x[ 28];
            r_state_x[ 84] <= r_state_x[ 19] ^ r_state_x[ 40] ^ r_state_x[ 88] ^ r_state_x[ 24] ^ r_state_x[118];
            r_state_x[ 85] <= r_state_x[ 83] ^ r_state_x[ 77] ^ r_state_x[ 97] ^ r_state_x[ 50] ^ r_state_x[ 10] ^ r_state_x[118];
            r_state_x[ 86] <= r_state_x[126] ^ r_state_x[112] ^ r_state_x[ 64] ^ r_state_x[107] ^ r_state_x[ 88];
            r_state_x[ 87] <= r_state_x[ 83] ^ r_state_x[ 25] ^ r_state_x[ 40] ^ r_state_x[ 20] ^ r_state_x[  2] ^ r_state_x[ 75];
            r_state_x[ 88] <= r_state_x[ 32] ^ r_state_x[ 37] ^ r_state_x[111] ^ r_state_x[ 51] ^ r_state_x[ 99];
            r_state_x[ 89] <= r_state_x[ 11] ^ r_state_x[120] ^ r_state_x[ 18] ^ r_state_x[ 84] ^ r_state_x[ 26] ^ r_state_x[ 52];
            r_state_x[ 90] <= r_state_x[123] ^ r_state_x[101] ^ r_state_x[ 66] ^ r_state_x[ 68] ^ r_state_x[  1];
            r_state_x[ 91] <= r_state_x[  8] ^ r_state_x[ 68] ^ r_state_x[123] ^ r_state_x[116] ^ r_state_x[ 23] ^ r_state_x[122];
            r_state_x[ 92] <= r_state_x[ 56] ^ r_state_x[ 31] ^ r_state_x[ 78] ^ r_state_x[ 36] ^ r_state_x[ 42];
            r_state_x[ 93] <= r_state_x[ 38] ^ r_state_x[ 40] ^ r_state_x[ 89] ^ r_state_x[  4] ^ r_state_x[111] ^ r_state_x[ 73];
            r_state_x[ 94] <= r_state_x[ 63] ^ r_state_x[118] ^ r_state_x[109] ^ r_state_x[ 46] ^ r_state_x[ 44];
            r_state_x[ 95] <= r_state_x[ 92] ^ r_state_x[ 53] ^ r_state_x[110] ^ r_state_x[ 52] ^ r_state_x[119] ^ r_state_x[ 40];
            r_state_x[ 96] <= r_state_x[ 69] ^ r_state_x[  2] ^ r_state_x[ 72] ^ r_state_x[  3] ^ r_state_x[120];
            r_state_x[ 97] <= r_state_x[ 43] ^ r_state_x[ 17] ^ r_state_x[ 14] ^ r_state_x[106] ^ r_state_x[122] ^ r_state_x[ 69];
            r_state_x[ 98] <= r_state_x[ 70] ^ r_state_x[ 41] ^ r_state_x[ 60] ^ r_state_x[ 51] ^ r_state_x[ 13];
            r_state_x[ 99] <= r_state_x[ 18] ^ r_state_x[ 74] ^ r_state_x[ 75] ^ r_state_x[100] ^ r_state_x[ 61] ^ r_state_x[ 60];
            r_state_x[100] <= r_state_x[115] ^ r_state_x[ 38] ^ r_state_x[ 92] ^ r_state_x[ 65] ^ r_state_x[  4];
            r_state_x[101] <= r_state_x[ 75] ^ r_state_x[ 34] ^ r_state_x[ 44] ^ r_state_x[ 72] ^ r_state_x[ 79] ^ r_state_x[ 63];
            r_state_x[102] <= r_state_x[ 57] ^ r_state_x[  2] ^ r_state_x[ 20] ^ r_state_x[ 79] ^ r_state_x[ 27];
            r_state_x[103] <= r_state_x[ 45] ^ r_state_x[ 35] ^ r_state_x[109] ^ r_state_x[ 49] ^ r_state_x[ 39] ^ r_state_x[ 96];
            r_state_x[104] <= r_state_x[ 20] ^ r_state_x[ 90] ^ r_state_x[103] ^ r_state_x[ 60] ^ r_state_x[117];
            r_state_x[105] <= r_state_x[  6] ^ r_state_x[  3] ^ r_state_x[ 79] ^ r_state_x[115] ^ r_state_x[  8] ^ r_state_x[ 81];
            r_state_x[106] <= r_state_x[102] ^ r_state_x[ 36] ^ r_state_x[ 83] ^ r_state_x[112] ^ r_state_x[ 71];
            r_state_x[107] <= r_state_x[ 42] ^ r_state_x[126] ^ r_state_x[ 62] ^ r_state_x[113] ^ r_state_x[ 43] ^ r_state_x[ 30];
            r_state_x[108] <= r_state_x[ 50] ^ r_state_x[ 69] ^ r_state_x[ 35] ^ r_state_x[ 47] ^ r_state_x[113];
            r_state_x[109] <= r_state_x[104] ^ r_state_x[ 23] ^ r_state_x[ 65] ^ r_state_x[ 77] ^ r_state_x[ 67] ^ r_state_x[117];
            r_state_x[110] <= r_state_x[ 44] ^ r_state_x[ 68] ^ r_state_x[  0] ^ r_state_x[ 80] ^ r_state_x[ 19];
            r_state_x[111] <= r_state_x[ 20] ^ r_state_x[ 27] ^ r_state_x[114] ^ r_state_x[105] ^ r_state_x[101] ^ r_state_x[ 66];
            r_state_x[112] <= r_state_x[ 43] ^ r_state_x[119] ^ r_state_x[116] ^ r_state_x[109] ^ r_state_x[ 21];
            r_state_x[113] <= r_state_x[116] ^ r_state_x[ 70] ^ r_state_x[  0] ^ r_state_x[105] ^ r_state_x[ 71] ^ r_state_x[  4];
            r_state_x[114] <= r_state_x[ 72] ^ r_state_x[ 22] ^ r_state_x[115] ^ r_state_x[ 43] ^ r_state_x[ 34];
            r_state_x[115] <= r_state_x[ 91] ^ r_state_x[ 21] ^ r_state_x[ 45] ^ r_state_x[104] ^ r_state_x[ 74] ^ r_state_x[105];
            r_state_x[116] <= r_state_x[ 58] ^ r_state_x[103] ^ r_state_x[ 30] ^ r_state_x[ 13] ^ r_state_x[108];
            r_state_x[117] <= r_state_x[  5] ^ r_state_x[ 97] ^ r_state_x[ 71] ^ r_state_x[  0] ^ r_state_x[ 47] ^ r_state_x[  9];
            r_state_x[118] <= r_state_x[ 22] ^ r_state_x[ 35] ^ r_state_x[124] ^ r_state_x[126] ^ r_state_x[120];
            r_state_x[119] <= r_state_x[ 52] ^ r_state_x[ 66] ^ r_state_x[106] ^ r_state_x[ 11] ^ r_state_x[104] ^ r_state_x[ 17];
            r_state_x[120] <= r_state_x[ 38] ^ r_state_x[ 64] ^ r_state_x[  7] ^ r_state_x[102] ^ r_state_x[ 24];
            r_state_x[121] <= r_state_x[ 10] ^ r_state_x[ 90] ^ r_state_x[ 25] ^ r_state_x[ 81] ^ r_state_x[ 92] ^ r_state_x[ 77];
            r_state_x[122] <= r_state_x[ 19] ^ r_state_x[ 60] ^ r_state_x[ 87] ^ r_state_x[ 92] ^ r_state_x[ 48];
            r_state_x[123] <= r_state_x[ 11] ^ r_state_x[ 95] ^ r_state_x[ 27] ^ r_state_x[ 36] ^ r_state_x[ 22] ^ r_state_x[ 98];
            r_state_x[124] <= r_state_x[  9] ^ r_state_x[ 23] ^ r_state_x[ 81] ^ r_state_x[ 44] ^ r_state_x[ 93];
            r_state_x[125] <= r_state_x[ 49] ^ r_state_x[ 73] ^ r_state_x[ 88] ^ r_state_x[ 98] ^ r_state_x[112] ^ r_state_x[121];
            r_state_x[126] <= r_state_x[ 48] ^ r_state_x[ 70] ^ r_state_x[ 86] ^ r_state_x[ 23] ^ r_state_x[ 59];
            r_state_x[127] <= r_state_x[ 97] ^ r_state_x[ 29] ^ r_state_x[ 48] ^ r_state_x[110] ^ r_state_x[ 34] ^ r_state_x[107];
            
            r_state_y <= v_state_y2;
            
        end
    end
    
endmodule

