-- Copyright (c) 2020-2021 Maarten Baert <info@maartenbaert.be>
-- Available under the MIT License - see LICENSE.txt for details.

-- This file was generated by `generate_vhdl.py`.

library ieee;
use ieee.std_logic_1164.all;

entity xormix64_tb is
end xormix64_tb;

architecture bhv of xormix64_tb is
    
    -- configuration
    constant streams : integer := 4;
    constant results : integer := 100;
    constant seed_x  : std_logic_vector(63 downto 0) :=
        X"91eb2642dd235c45";
    constant seed_y  : std_logic_vector(64 * streams - 1 downto 0) :=
        X"76151b36c1b25d925fe5385d7b0d285ce1fb2a562c946e0ee02c9cdec24e8b50";
    
    -- reference result
    type result_array_t is array(0 to results - 1) of std_logic_vector(64 * streams - 1 downto 0);
    signal ref_result : result_array_t := (
        X"76151b36c1b25d925fe5385d7b0d285ce1fb2a562c946e0ee02c9cdec24e8b50",
        X"06059f171acf0136b7dd4058c006162e232ff81497a486174d50dcc76171dd41",
        X"536a7ab5fc92c206ece7d74d471469a40550f30646e1307d17cf38f26e0b3c7d",
        X"e767915c3bd0739a5b78dd94922bd38b3914d22b0ff7aa7c2a8697491d569a24",
        X"cb418d6f81c092abba5bffc5c79ce508146210100f8b141a55c92c5d23876a98",
        X"cf1521f53afaa9e6b94363df6e095facd8b161554de2c1702c1c77be18f3ea67",
        X"2b1734e9e0169184efb407a4fa74a50c810b13c1c8727572509bd376fd0cf594",
        X"45e10a0aaa07a16c510feef2d758b258d94d13fe2d7cea56f81c5d17754cdadf",
        X"20be83a48e55a429e953d1150c6d2df3eaedc2c462f5014f38699c328ce6ad7d",
        X"40305375a4ecbc98d2b76c3bd2d33a30f9ba46dae25505e338be7ed9537c6dd4",
        X"918db42f057906a7a8b95fc68f65ae02fea97c7897314ee835d9f50ce49973b6",
        X"cff445a8ebc8e72daf634072a6da2d69609ddd9a7243986c410da68b0b6b3a48",
        X"5351bb04cd89a363acf2fae68fa0eadd0951d3dae6c2ea89fca0322824a468cd",
        X"9fadc80975ad9cade9df284c9f390fc086d38dae6320470b867862cf68965539",
        X"6b3caf0e314c054fa4d4217fd605e3262116fd456787a1d49e1ca1c3846e5ef9",
        X"d95eaeecaa7833c6dba6c3caadb4e2dbfed0467b1358239aff7f71dfa464defd",
        X"462ebcb9b7b4714dfa8f1bc3d775d485e1be5e4e0c79313a799abed790af3970",
        X"fff50d19b8a2aa576a8cefb42123afc29e862566bf5d376c5477da2759facfe4",
        X"6115e04b79ec85c5ab235d8e1fcd3f5faebefe03fb4c3880cd801ff67511a763",
        X"a69643bcab3b43ca8d1afdf7d509419c7270a60fa69b7fc92f00728010a214e2",
        X"b31f7d12afbffc06c89a4e45b00f1a399d127ba8a077f332823084607fa68d96",
        X"73a5d1f13a7d9d45102de000e67e039c4e387b35b60f9284dcfadb0c2b3661a0",
        X"fdd7c0a023a37bbd772d51759553e03b8db6d4e0f1e67dd0666dd8ed27c01c07",
        X"c7f80275311c24c2c9fa1fc9ab316d0217ed87bcc99d801ef79909d8aa589817",
        X"05258c4a5f95bf995b139743ebb9f6bfded444d632989be2fe5f1848a9c22bc7",
        X"99ce50117150d69e537c472da767f56829fdbbfa1ba10fc84ef76bd38b4ce6a2",
        X"dbf5f77a26bc94072aa96d65369e6fe1ecb34f6b9a2065003018289eaaf5afb7",
        X"68de25a1a6e9edf5f2411fa205c8ef39de5a7b657409a2acba96501f3bbfe54f",
        X"304c48c8a24153475ab456533a0aa86a50949b47934748060141b5d35b80f430",
        X"c47d42ededca1013100eeeb7fdb92148786033c592c10d4b7546aecacdac9002",
        X"42de317bebdde347759ec8a49f142447c3cf4448abbc83f4210ea8e03c72f5b8",
        X"51e8ea4d7420721275e932399a0cc3f52f962e2f7933c90f8c2cfd32231e7f8e",
        X"d4d9f34dfd0c45091665a0cdf0e290ed3b91c80f23123273e88f5045ee3f442e",
        X"0b36d27498c2374efe845f83f72fa81a16ee9755db18b6cf941d4d083251b464",
        X"02469ee6454d9efcc78fe3a6b21a6c8c1efa4ce8317c3f1141eb80e608ce8567",
        X"1df8b262d1c2950cd11585373297a7eb70c8a456903c872e01f776788c478d45",
        X"bba47b93389d9d33b423a5c10bd2b166fb982377bb6f655cd1e80bb723cff087",
        X"da9cbea7fc3694f3781bd0a36bd74490fdd2f4da2e59d27064e120c559976760",
        X"fe026232904ed1258df1f90957fb14005d097187eab90ba2e1162b23cdbf4640",
        X"692782593edea6b3d4ed6855ea34eb9e397feb0dc60f1bffca2b7014e380dbe4",
        X"5729d77cd3c74701bcf04219b4f88d72cdedfa3ee36b2fbef700096b551abfbc",
        X"62965ecc7532bec51a2cb9255c1504818e642808a7386334bc9c5f3e4d412dce",
        X"52162f49ad57b9eb6ded1eed60f1fcf7e9290e707870cb077e4900b6ece6890e",
        X"07df1f18ad5c3b2febb9c5fe0eb20e03abc287ab05abdbf15ddb42f4b4c2d528",
        X"7927a74ff1e45873f8e51eff63b040abe5fad5ea1804cf207201050cd848112d",
        X"b60f854a454cab5bd94dfbfcbba7af087b90d8a7d6f5905d8e3c9e0356522beb",
        X"6baca6516566e85362f9f8ba23ef2ec26cdbc03b4ab6ac7cd0b583857b8a696d",
        X"48a9e39bdffd730af78612e7d2eb427c0803cf15ab1fdf6bde66346de1994d79",
        X"5c7e911ba61eff000bf367eb357edc4b41ee132bb0a6e6587f2349070599ded1",
        X"c865b27377e40661d957d1d5d6496ea0211abcddd38e4c4d9d0a039476effd29",
        X"7cb6b6ca2b8ce247193c45a28044d9e75939511526be5aa36750b493841c7885",
        X"ff7490f839aa5ce6bd0e9559df559abca5a93b69b9345c5c72f43cffbe10db51",
        X"e27c5878fd62cd24a786002f3ea9d678783b011c29f4ef4a171a22aa835f1a41",
        X"d39d3585930aeb78efcbad9460e284c1aaee000c411e45d1577dd76345c9589f",
        X"c6638c1480fe6dea2329649b34a0bf6a1d4a40c57197d9a3776b55225fa2c6ab",
        X"7ec6ac0b4d45c00dd5160f93a09f895b52f83f996a1775ce9406173c18723234",
        X"0f9bcc7752988971dedc044eaec9d8b935b8553bedeb1eefcfd58fed77306ccf",
        X"21857a740be7722dc80b83bdd1f08ba8905494a0441b800a625990fed3e681ef",
        X"aa9f1321480f9ed8a6141986ed9b7ebd8d61f19fc3471f5a4321888d48ad1fd8",
        X"eca6f58225519f8856731f422781ca2e6a0c451f37f14713f990c2efb417f29c",
        X"eabdba893276efea4c26f62097057e2b44e0af5ba81cc755354dc74010bec162",
        X"a057c321e758660ef0750ef0c9f06f32341a6e97deac55d6315ed5686b332d11",
        X"51afbf7d4c5f152fffd552822fa81f99c2d44a4f9931559b3a66dfd0deb74c51",
        X"4c8cde94a046c53791890220421e4c5faeb02f0d497ae32f03d05577d12af514",
        X"f3e6f429acaa12a53ccd3b06019657df09d8fdad9c10ca9eecee17f1f9627893",
        X"9ecb404930b63592e047649eaeed6d59171fec374d722efa214519b517b9d42b",
        X"875d604b29993bcf53db247fa72dfdabbc491cb72249fb1bf4e4f59087cc7d53",
        X"4b4b5fe7c8e5a90251a65ee6ddb2cc8bf4707a85601220f260d4daadaa96c1f7",
        X"d996432106a156d4550290b2184f9fc740ebc2ebbedcf26a264e5616bf376f32",
        X"add01153700af22b6f0caf93908177480cb314a56352300665cae8fea438a5ec",
        X"2e63aa6cc6b693a783483c86a6dc89895d05bd9bb4ce675fc7825c583c984298",
        X"2793a24e6dc95cd4d4acb1d2f670085657372f1aebdf819ad2290309acf6edf8",
        X"8edafd98f8e833ae9b8770123d27c8436124330669261f1199e65962b6e831e6",
        X"1774d258be5b2608fa390f818a0210c890e4150b06d02a8c7527f8160e1e9805",
        X"36d92b6d186a53472f0c3a321a0c49f8ea343ca766121ab9c654d65aecd750bc",
        X"cb2b0862b0482af45aec7919ee5e1c809c84424f312f591a684bca05de44eee0",
        X"7a5980bae16ea77ed7774fae770dbf7e0ed563f17a87af5a424b57895f3bbd94",
        X"bd8d852b2008fd7f4ee4961755925c4ef409b50fbfc8dfd3bfc16c8d003edc86",
        X"2679d6d3558eb761133cfd934b3fe69f49d58425249c84d889be114afe847078",
        X"4d2df2094f70deaf731f0c79eca6320075373f4d584ccb576a43c1e84ad789ee",
        X"1c03eda2a5d051194d81f3a157bcec459a302cbe7af193ccb9a4af5b1fffa150",
        X"f2271ff2e2eeb246267c983e0848289a9440ff035c0fca63faac9a782704e832",
        X"159f76edd72742f2f9ff50d40314680643adc51f355caaad152be89898cf3394",
        X"00f47259e18c553126f2d991928c7227b31b298f7cb2b9361e76567b70c4f2d7",
        X"bc3018f32ee8421d0ed9d4b0253060010f6b7c815a9d9e9da64a8c74e0c88cf1",
        X"060bca70bff395235a40b835439de2efbb1e43f0f6339cd00b39a7c6570c6b72",
        X"228f6130d4ef03ab0908ad07d2058f520346d201ce0cf7ccb1c18cc58a568a57",
        X"6397c7539511be60d397303cdbb6d6e0ca57e60ad6a4fa5460242b0c8be0f68d",
        X"ee78c4d92722fc7debce29ead5b71abdd92f3065567d9c559c6b76836c78252e",
        X"93c443370d87232d6f85eacffd8aacdea95913663fdd1716ef25110b36078d56",
        X"46e16ccc9876d35646541d60bd29d1d93b698c83000754e7585ce405db6de0af",
        X"453a40765e0e6efe146f281d29226fbf4a67e56160c98353c99c8bdfa72dadee",
        X"df49ac65d4e648ec3f3981f0c113504753130adf7628aabc18860859140fed18",
        X"ea8659b46ef95e187e76339ddb351168c1fe5e32bcae9232109465a05fd454a0",
        X"2e549659edb88e260cc78757d61ea347898c3a1fe80501700992c4a31e21b496",
        X"0eb0ce98a96064428b34fafce63007db685f64bbd5c18979d1a51437a1d65330",
        X"caa0bd50800062a88e1e794a36429a7985dd7ede6c3537fd348fb3c664bb21d9",
        X"d3bbada9bdba34f3214907f617624372d4bed7cb38f3b3110cbd65996384338c",
        X"01790a8cfd247b3160cc786d8f71e7f89e65043b8ecbc27b5ef100162f12f946",
        X"e17f162e014559465ab2bdd60b5ee05edccd049f0b07da87b3313f1ce0fd8e9a"
    );
    
    -- DUT signals
    signal clk    : std_logic := '0';
    signal reset  : std_logic;
    signal enable : std_logic;
    signal result : std_logic_vector(64 * streams - 1 downto 0);
    
    -- flag to stop simulation
    signal run : boolean := true;
    
begin
    
    -- DUT
    inst_xormix : entity work.xormix64 generic map(
        streams => streams
    ) port map (
        clk    => clk,
        reset  => reset,
        seed_x => seed_x,
        seed_y => seed_y,
        enable => enable,
        result => result
    );
    
    -- clock process
    process
    begin
        while run loop
            clk <= '1';
            wait for 5 ns;
            clk <= '0';
            wait for 5 ns;
        end loop;
        wait;
    end process;
    
    -- input/output process
    process
    begin
        wait until rising_edge(clk);
        reset <= '1';
        enable <= '0';
        wait until rising_edge(clk);
        reset <= '0';
        enable <= '1';
        for i in 0 to results - 1 loop
            wait until rising_edge(clk);
            assert result = ref_result(i) report "Incorrect result" severity warning;
        end loop;
        run <= false;
        wait;
    end process;
    
end bhv;

